= Angelica Root

_Scope: This entry treats *Angelica archangelica* L. (European / garden angelica), the "angelica root" of the Galenic–Tibb–Western herbalist tradition. The East Asian Angelicas — A. sinensis (當歸 dāngguī), A. dahurica (白芷 báizhǐ), A. pubescens (獨活 dúhuó) — are distinct canonical drugs in Chinese medicine, each with its own profile and clinical niche, and warrant their own entries; they are discussed comparatively in the Chinese-medicine section below. The Himalayan A. glauca, sometimes identified with the contested Sanskrit_ coraka, _is noted in the Ayurvedic section. Ayurvedic status of A. archangelica: reasoned-only, no classical entry. Tibb status: post-classical (late post-medieval introduction; not in the Avicennan / al-Bayṭār canon). Chinese status: not in the classical Chinese materia medica — treated by reasoned extension on classical axes._

== Nomenclature & Etymology

*Latin:* _Angelica archangelica_ L. (= _Archangelica officinalis_ Hoffm.), family Apiaceae (Umbelliferae); the principal drug is the dried *root and rhizome* (_Angelicae radix_), with the seed (_fructus_) and crystallized stems also in dietetic-medicinal use. Medieval Latin _angelica_ from Late Latin _angelicus_ "angelic, of the angel" (from Greek ἄγγελος _ángelos_, "messenger"); the species epithet _archangelica_ intensifies — "angelic-of-the-archangel." Several folk-etymological origin stories circulate: an archangel revealed the herb to a monk during plague; the plant flowers around the feast of the Annunciation in some Northern European reckonings; the species blooms near May 8th, the Eastern feast of the Archangel Michael. These are folk etymologies of the *plant-naming*, not of the Latin word — the lexical line itself is simply "an angelic plant," a medieval coining honoring the herb's plague-remedy reputation.#footnote[Etymology: Lewis & Short, _A Latin Dictionary_ (s.v. _angelicus_); _Oxford English Dictionary_ (s.v. "angelica, n."). The medieval naming-tradition (angel-revelation origin stories) is folk; the standard lexical line is simply Late Latin _angelicus_ "angelic" applied to a herb of high regard — see Marzell, _Wörterbuch der deutschen Pflanzennamen_, s.v. _Angelica_. The plant is genuinely an angelic-of-the-archangel intensification, attested in late-medieval Latin pharmacy texts.]

*English:* _Angelica_, _garden angelica_, _Holy Ghost_, _archangel_, _wild celery_ (a misleading folk name in some regions, since the closely-related _Angelica sylvestris_ is also called wild celery); _masterwort_ in some regional usage, although the proper _masterwort_ is _Peucedanum ostruthium_ (a related Apiaceae). The English name is borrowed transparently from medieval Latin via Old French.#footnote[_Oxford English Dictionary_ (s.v. "angelica, n.", "masterwort, n."). The masterwort / angelica regional naming-conflation is documented in standard ethnobotany.]

*Chinese:* A. archangelica has *no classical Chinese name and is not a canonical drug in the Chinese tradition*. Modern Chinese: 西洋當歸 (xīyáng dāngguī, "Western dāngguī") or 歐當歸 (ōu dāngguī, "European dāngguī"); these are modern coinages. *The classical Chinese tradition treats three different Angelica species as three distinct canonical drugs* — they are not interchangeable, and none is a substitute for the European species:

- *當歸 (dāngguī)* — _Angelica sinensis_ (Oliv.) Diels. "Should/ought-return," from the formula-naming tradition: per Li Shizhen's _Bencao Gangmu_, the name relates to the herb's blood-returning action (in some readings, also to its use in returning a husband to a wife — a folk register). The single most important "women's herb" of TCM.
- *白芷 (báizhǐ)* — _Angelica dahurica_ (Fisch. ex Hoffm.) Benth. & Hook. f. "White zhǐ," with 芷 being a poetic root-name. The canonical Yangming-channel surface-releasing / wind-damp / sinus / headache drug.
- *獨活 (dúhuó)* — _Angelica pubescens_ Maxim. f. _biserrata_ Shan et Yuan. "Alone-living," referring to the solitary upper stem unmoved by wind. The canonical lower-body wind-damp _bi_ drug, paired contrastively with _qiānghuó_ (羌活, _Notopterygium incisum_) which addresses upper-body wind-damp.

(Compare 川芎 _chuānxiōng_, _Ligusticum chuanxiong_ — same family, different genus, often paired with 當歸 in formulas but a distinct drug.)#footnote[Character glosses and species assignments: _Bencao Gangmu_ (本草綱目), 1578 — 當歸, 白芷, 獨活 entries; Bensky, Clavey & Stöger, _Chinese Herbal Medicine: Materia Medica_, 3rd ed. (Eastland Press, 2004). The naming of 當歸 ("should-return") is folk-etymologized variously in classical commentary — Li Shizhen offers both the blood-returning and the husband-returning readings. The non-substitutability of the three Chinese Angelicas (and the European species) in classical formulas is a textbook materia-medica point.]

*Sanskrit:* *No classical Sanskrit name* for _A. archangelica_. The herb is not entered in the saṃhitās, nighaṇṭus, or major commentarial pharmacy literature — A. archangelica is a northern European species, outside the geographical range of the Indian classical pharmacopoeia. The Sanskrit name *चोरक (coraka)* in classical commentary refers (where it refers to Angelica at all) to a Himalayan aromatic root, most commonly identified by modern dravyaguna (P. V. Sharma) with *_Angelica glauca_ Edgew.* — a distinct Himalayan species, not _A. archangelica_. The identification is contested: alternative classical readings give _coraka_ as _Selinum vaginatum_, _Pleurospermum_ spp., or other Himalayan umbellifers. The Hindi/modern term for the European A. archangelica is simply transliterated _enjaleekā_ or descriptive _vilāyatī coraka_ ("foreign / European coraka") in modern Ayurvedic pharmacy texts — itself a modern coinage.#footnote[Monier-Williams, _A Sanskrit–English Dictionary_ has _coraka_ as "a fragrant grass or plant used as a perfume," with identification unsettled. P. V. Sharma, _Dravyaguṇa-vijñāna_, vol. II, treats _coraka_ = _Angelica glauca_ (Himalayan); other classical commentators give _Selinum vaginatum_ or other umbellifers. The European A. archangelica is *not* in the classical Indian record — flagged as a modern, post-canonical introduction.]

*Arabic / Persian / Urdu (Tibb register):* The classical Arabic-Islamic medical tradition does *not* include _A. archangelica_ — the herb's native range is northern Europe (Iceland, Faroes, coastal Norway, Lapland, the Baltic), outside the Mediterranean / Persian / Indian range of the classical pharmacopoeia. *Avicenna's al-Qānūn does not have an entry; Ibn al-Bayṭār's al-Jāmiʿ does not have an entry. A. archangelica enters Tibb as a post-medieval European introduction*, beginning in earnest in the 17th–19th c. via European-Unani contact in South Asia. Modern Unani pharmacopoeias under AYUSH list the herb under transliterated names: انجلیکا / انجليكا (_anjlīkā_); حشيشة الملاك (_ḥashīshat al-malāk_, "herb of the angel" — a Persian-Arabic calque of the European name); Maghrebi folk حبة الملائكة (_ḥabbat al-malāʾika_, "seed/grain of the angels"). The "_malāʾika_" naming-line tracks European _angelica_ through Arabic / Persian translation; it is *not* a classical Tibb name.#footnote[Verified absence in the classical Tibb canon: Ibn Sīnā, _al-Qānūn fī al-Ṭibb_, Book II (_al-Adwiya al-Mufrada_); Ibn al-Bayṭār, _Kitāb al-Jāmiʿ li-Mufradāt al-Adwiya wa-l-Aghdhiya_ — neither classical text treats A. archangelica. Modern Unani listings: AYUSH Ministry of India, _National Formulary of Unani Medicine_ — under the modern transliterated names. The folk-Arabic "_ḥabbat al-malāʾika_" naming is a translation calque of the European _angelica_ and post-dates the classical pharmacopoeial tradition — flagged.]

*Norse / Sami / Old Icelandic:* The *oldest documented European medicinal-plant tradition* for angelica is northern, pre-Christian, and indigenous. Old Norse / Icelandic: *hvönn* (hvönnin, "the angelica"); Old Norwegian / Faroese / modern Norwegian: *kvann*, *kvannerot* (root); Swedish: *kvanne*, *angelika*; Danish: *kvan*; Sami northern: *boska* (or *fáddnu* in some dialects, with subspecies distinctions). The medieval Icelandic law-code *_Grágás_* (12th–13th c.) regulates the harvesting of wild _hvönn_ from communal lands — one of the earliest legal protections of a medicinal plant in any northern European vernacular tradition. The *hvannagarðr* (angelica garden) was a recognized agricultural feature of Icelandic homesteads.#footnote[Old Norse / Icelandic _hvönn_ and the _Grágás_ regulation: standard Icelandic legal-historical literature (e.g. Dennis, Foote, & Perkins, _Laws of Early Iceland: Grágás_); modern Norwegian / Sami ethnobotany — Høeg, _Planter og Tradisjon_; Svanberg on Sami ethnobotany. The northern indigenous tradition genuinely predates the Christian / medieval Latin naming of the herb.]

== Classical Chinese Medicine (中醫) View

_A. archangelica has no classical Chinese entry._ The Chinese tradition treats the *three different East Asian Angelica species* as three distinct canonical drugs, each with its own property / flavor / channel placement and clinical niche; the European species is not a recognized substitute for any of them and would not be used in their place in classical formulas. The Chinese-medicine reading below is a *brief comparative orientation* on the three canonical Chinese Angelicas (each warranting its own future entry), followed by a *reasoned-extension* reading of A. archangelica on classical axes.

*The three canonical Chinese Angelicas (bare distinguishing profiles):*

- *當歸 (Angelica sinensis):* sweet, pungent, slightly bitter; *warm* (溫); Liver (肝), Heart (心), Spleen (脾) channels. Actions: 補血 (tonifies blood), 活血 (moves blood — head 當歸頭 tonifies, tail 當歸尾 moves more strongly, body 當歸身 balanced), 調經 (regulates menstruation), 止痛 (stops pain), 潤腸 (moistens intestines). The single most important blood-tonic of TCM and the canonical women's medicine. Distinctive use of *parts of the root* — head, body, tail — for different actions is a fine-grained classical refinement.
- *白芷 (Angelica dahurica):* pungent; warm (溫); Lung (肺), Stomach (胃), Large Intestine (大腸). Actions: 解表散風 (releases surface, scatters wind), 通鼻竅 (opens nasal orifices — for sinusitis, _bítì bùtōng_), 燥濕止帶 (dries damp, stops leukorrhea), 消腫排膿 (reduces swelling, drains pus). Distinctive: the *Yangming-channel* / forehead headache use.
- *獨活 (Angelica pubescens):* pungent, slightly bitter; warm (溫); Kidney (腎), Bladder (膀胱), Liver (肝). Actions: 祛風除濕 (dispels wind-damp), 通痺止痛 (frees obstruction, stops pain), 解表 (mild surface-releasing). Distinctive: *lower-body* wind-damp _bi_ (vs. upper-body, addressed by 羌活 qiānghuó). The canonical lower-body joint and lumbar wind-damp drug.

*Reading A. archangelica by reasoned extension (flagged):* Given its Tibb mizāj (Hot, Dry — see below), its pungent-bitter aromatic-resinous carminative profile, the European warming-stomachic use, and its native cold-damp climate (compensated by warming-drying-aromatic action), a reasoned classical-Chinese placement would be:

- *Property:* warm (溫), close to hot (熱) — the resinous intensity is somewhat above 當歸.
- *Flavor:* pungent (辛), with mild bitter (苦) note.
- *Channels:* Spleen (脾), Stomach (胃), Lung (肺), Kidney (腎) — the carminative-warming-aromatic profile maps to Spleen-Stomach (digestion), Lung (respiratory aromatic), and Kidney (warming yang against cold-damp).
- *Actions (read by extension):* 溫中散寒 (warms the middle, scatters cold), 行氣 (moves qi), 化濕 (transforms damp), 止咳化痰 (stops cough, transforms phlegm — for cold-pattern productive cough), 祛風除濕 (dispels wind-damp), 消食 (disperses food stagnation).
- *Cautions:* yin-vacuity heat, blazing fire, hypertension with heat-pattern, pregnancy at therapeutic doses (strong warming-moving), 陰虛火旺 (yin-vacuity with blazing fire).#footnote[The reading is reasoned extension on classical axes — *not* a canonical 本草 entry. The placement is supported by the herb's documented warming-aromatic-carminative pharmacology, its Tibb Hot-Dry mizāj, and its European stomachic / respiratory / antirheumatic use; the warm-pungent / Spleen-Stomach-Lung axis is the standard classical placement for this profile, with comparable warm-pungent umbellifers (小茴香 fennel, 八角 star anise) as the proximate classical analogues. Flagged as reasoned-only.]

== Ayurvedic Dravyaguna (द्रव्यगुण)

_Reasoned analysis, not classical for A. archangelica._ The herb has no entry in Caraka, Suśruta, Aṣṭāṅga Hṛdaya, or the major nighaṇṭus. The Himalayan *_Angelica glauca_* (often identified with the contested Sanskrit _coraka_) is taxonomically a cousin and has its own incipient dravyaguna placement in modern commentarial literature — but is a *distinct drug* from the European A. archangelica. The reading below applies dravyaguna principles to A. archangelica *by reasoned extension*, in the same register as oats or tea: principled application, not canonical citation.

*Rasa (taste):* Kaṭu (कटु, pungent), Tikta (तिक्त, bitter) — the standard reading for a warming-aromatic-resinous umbellifer.

*Guṇa (qualities):* Laghu (लघु, light), Rūkṣa (रूक्ष, dry), Tīkṣṇa (तीक्ष्ण, sharp / penetrating), Sugandhi (सुगन्धि, fragrant — a recognized guṇa-line for aromatic dravyas). The set is the precise inverse of cooling-snigdha _madhurikā_ (fennel, in the Ayurvedic reading), but converges with _hiṅgu_ (asafoetida) and _ajamodā_ (caraway / ajwain — depending on identification).

*Vīrya (potency):* Uṣṇa (उष्ण, heating) — strong convergence with the Tibb Hot mizāj and the Galenic warming reading; *divergence* from the Ayurvedic śīta vīrya of fennel.

*Vipāka (post-digestive taste):* Kaṭu (कटु, pungent) — predicts a *Vāta-Kapha-pacifying / Pitta-aggravating* doṣa profile and an _aknulomana_-rather-than-bṛṃhaṇa action.

*Prabhāva (specific action):* *No prabhāva can be assigned with classical authority*, since A. archangelica is not a classical dravya. A modern dravyaguna-style reading could note the *furanocoumarin-mediated photosensitization* as a prabhāva-level effect (not predictable from rasa-guṇa-vīrya-vipāka — phototoxicity is genuinely _aprākṛta_ in that sense); but this is a modern interpretive move with no classical authority — flagged.

*Doṣa effect:* Kapha-Vāta-śāmaka (pacifies Kapha and Vāta via the warming-drying-aromatic profile); aggravates Pitta in excess (uṣṇa-tīkṣṇa).

*Karma (read by extension):*
- _Dīpana, Pācana_ — kindles digestion; supports _āma_-resolution.
- _Vāta-anulomana_ — relieves Vāta downward (gas, bloating, intestinal cold-cramp).
- _Mūtrala_ — modest diuretic.
- _Kāsahara, Śvāsahara_ — anti-cough, anti-asthma (for cold/damp productive cough; aligns with the European respiratory aromatic register).
- _Jvarahara_ — anti-fever (the European antipyretic / sudorific use, by extension).
- _Hṛdya_ — cardiotonic-mild (by extension from the Western "warming heart-tonic" reading, modest).
- _Garbhāśaya-uttejaka_ — uterine-stimulant (the emmenagogue / pregnancy-caution profile).
- _Manasika-prasādana_ — mood-elevating (paralleling the Tibb _mufarriḥ_ category and the Western "anxiolytic bitters" reputation; modest).
- *Used in (modern reasoned context):* flatulence and cold-pattern dyspepsia (_agnimāndya_, _ādhmāna_), cold/damp productive cough (_kapha-kāsa_), articular cold-damp (_āma-vāta_, by extension), mild fever (cold-pattern), scanty menstruation with caution.

=== Viruddha (विरुद्ध — incompatibilities)

_(tagged by source tier — S = core saṃhitā, N = later nighaṇṭu, F = folk/regional, M = modern/pharmacological. Note: no classical viruddha entries for A. archangelica; (S) / (N) below are extensions of conditional rules to a non-canonical substance.)_

- *(S, extended) Conditional (doṣa / avasthā) viruddha:* Pitta excess, _amlapitta_ (hyperacidity), _raktapitta_ (bleeding disorders), inflammatory states — the uṣṇa-tīkṣṇa profile is inappropriate. The classical principle (uṣṇa-tīkṣṇa-rūkṣa not for Pitta-rakta) applies straightforwardly.
- *(N, extended) Combination cautions:* hot pungent-aromatics with sour-fermented foods may compound Pitta heat (standard saṃyoga rule); large doses of warming-aromatic resinous herbs are cautioned in hot summer regimen (_grīṣma-kāla_) per general _kālajñāna_ rules.
- *(M) Modern medical:*
  - *Pregnancy* — emmenagogue and uterine-stimulant: avoid therapeutic doses; small culinary use (vermouth, crystallized stem, gin-flavored cooking) is generally considered safe.
  - *Furanocoumarin photosensitization* — bergapten, xanthotoxin (8-MOP), imperatorin, angelicin in the root and especially the aerial parts; topical contact and high-dose internal use combined with sun exposure can cause *phytophotodermatitis* (the same mechanism as giant-hogweed and bergamot burns). The signature modern caution for this herb.
  - *Anticoagulant interaction (theoretical)* — angelica coumarins are not strongly anticoagulant like dicoumarol, but combination with warfarin / NOACs warrants monitoring.
  - *Hypoglycemic effect (mild)* — combine cautiously with antidiabetic medication.
  - *CYP3A4 inhibition (in vitro)* — bergapten and imperatorin inhibit CYP3A4; potential interaction with CYP3A4-metabolized drugs; clinical relevance modest at typical doses but flagged.
  - *Apiaceae allergy* — cross-reactivity within the family (celery, parsley, carrot, fennel).
  - *The hemlock confusion (wild-harvested):* A. archangelica resembles *_Cicuta virosa_* (water hemlock — deadly) and *_Conium maculatum_* (poison hemlock — Socrates' executioner). Field identification — stem markings, root scent, flower-umbel structure, habitat — must be reliable. The single most important practical caution for wild-harvested angelica.#footnote[The Pitta-excess and conditional contraindications follow standard dravyaguna logic for uṣṇa-tīkṣṇa drugs — extended here from the classical principle, since A. archangelica has no classical viruddha-list of its own. (M) Photosensitization: documented in pharmacognosy and dermatology literature; ESCOP _Monographs_, _Angelicae radix_; standard reviews on furanocoumarin phytophotodermatitis. CYP3A4 in vitro inhibition: peer-reviewed phytopharmacology; clinical relevance modest at typical doses. The hemlock identification caveat is universal in wild-harvesting literature.]

== Traditional Arabic & Islamic Medicine (Ṭibb al-ʿArabī wa-l-Islāmī / Unani)

_A. archangelica is_ NOT _classical in Tibb._ The herb is a *northern European species*, outside the Mediterranean / Persian / Indian range of the classical Arabic-Islamic pharmacopoeia. Avicenna's *al-Qānūn fī al-Ṭibb* does not include A. archangelica; Ibn al-Bayṭār's *al-Jāmiʿ* does not include it; al-Rāzī's *al-Ḥāwī* does not include it. The herb enters Tibb as a *late post-medieval European introduction*, with substantive entry into modern Unani pharmacy in South Asia in the 17th–19th centuries. The reading below is *reasoned post-classical placement on the Galenic humoral axis* (by analogy with the canonical warm-dry aromatic umbellifers — _anīsūn_, _rāziyānaj_, _karawiyā_, _kammūn_), *not* classical Avicennan citation. See `tibb-al-arabi.typ` for the framework.

*Arabic:* انجليكا (_anjlīkā_) — transliterated; حشيشة الملاك (_ḥashīshat al-malāk_, "herb of the angel") and حبة الملائكة (_ḥabbat al-malāʾika_, "seed of the angels") — Maghrebi folk and modern Levantine usage, both being calques of the European _angelica_ name.

*Persian:* انجلیکا (_anjlīkā_); گیاه فرشتگان (_giyāh-e fereshtegān_, "herb of the angels") — a Persian translation of the European name. Modern Iranian Ṭibb-e Sonnati lists A. archangelica as a post-classical addition.

*Urdu / Hakeemi:* انجلیکا روٹ (_anjlīkā rūṭ_, "angelica root") — the standard modern Unani name in South Asia.

*Mizāj (reasoned placement, not Avicennan classical):* *Hot and Dry, between the 2nd and 3rd degrees* (Hot 2°–3° / Dry 2°), reading by analogy with the canonical warm-dry aromatic umbellifers of the *al-Qānūn* — _rāziyānaj_ (fennel: Hot 2° / Dry 2°), _anīsūn_ (anise: Hot 3° / Dry 2°), _karawiyā_ (caraway: Hot 3° / Dry 2°), _kammūn_ (cumin: Hot 3° / Dry 2°). The resinous intensity, the carminative-emmenagogue action profile, and the warming-respiratory use cluster A. archangelica in the upper range, comparable to _karawiyā_ / _anīsūn_. *Flagged as reasoned post-classical placement, not classical Avicennan citation.*

*Afʿāl (read on the canonical Tibb action vocabulary):*
- *Mufattiḥ li-l-suddad* — deobstruent (for hepatic, splenic, uterine obstruction — the classical Tibb reading of warming-aromatic-resinous umbellifers).
- *Kāsir li-l-riyāḥ* — carminative.
- *Mudirr li-l-bawl* — diuretic.
- *Mudirr li-l-ḥayḍ* — emmenagogue.
- *Muqawwī al-maʿida* — stomach-tonic.
- *Muḥallil al-balgham* — phlegm-resolvent (for cold-pattern productive cough).
- *Mufarriḥ* — mood-elevating; the modern Western "angelica as anti-melancholic carminative bitter" maps cleanly onto this canonical Tibb category. (Used in Tibb _mufarriḥ_ compound preparations by post-classical analogy.)
- *Muḍādd al-wabāʾ* — anti-pestilential. The medieval European plague-remedy reputation maps onto this Tibb category — flagged as reasoned analog placement, since classical Tibb plague-remedy formulas (those of Ibn al-Khatīb in al-Andalus, of Ibn Khātima in Almería, and the Persian _ṭāʿūn_ literature) do *not* include A. archangelica.

*Istemālāt (indications):* hepatic and splenic obstruction; cold-pattern dyspepsia; flatulence; amenorrhea / oligomenorrhea (cold-pattern); cold-damp productive cough; *amrāḍ al-balgham* (phlegmatic diseases); *amrāḍ al-rīḥ* (gas/wind disorders); melancholic states (under _mufarriḥ_).

*Mawāneʿ / Iḥtirāzāt:* *ṣafrāwī* (bilious / hot-pattern) constitutions and conditions; pregnancy (emmenagogue); concurrent anticoagulant therapy; epileptic patients (general caution for strong warming-aromatics); chronic high-dose use with sun exposure (the photosensitization caveat).

*Muṣliḥ:* *māʾ al-ward* (rose-water); *ṣamgh ʿarabī* (gum arabic); sugar / _sharbat_; *ʿasal* (honey) — the classical Tibb correctives for hot-dry intensity.

*Badal:* *anīsūn* (anise); *rāziyānaj* (fennel); *karawiyā* (caraway); *kammūn* (cumin) — the canonical warm-dry umbellifer carminatives. For the deobstruent / hepatic-clearing role, *kurkum* (turmeric) is a reasonable substitute.

*Classical Tibb formulas:* *None classical.* A. archangelica does *not* appear in *Sharbat-i Bazūrī*, *Joshānda-yi Rāziyānaj*, *Maʿjūn-i Falāsifah*, *Itrīfal* preparations, or other canonical Avicennan / Maghrebi-Andalusian / Unani _murakkabāt_ pre-dating the European introduction. Modern Unani compound preparations (AYUSH-listed, 19th c. onwards) sometimes include A. archangelica as a deobstruent-carminative adjunct, but these are *post-classical syntheses*, not classical formulas. The Western *Carmelite Water* (_Eau de Mélisse des Carmes_, early 17th c.) — a Discalced-Carmelite distillate of *melissa + angelica + nutmeg + lemon-peel + coriander + clove + cinnamon* — is the Western counterpart to the Tibb _ʿaraqiyāt_ (distilled-water class) and entered some colonial-era Unani practice as a borrowing.

*Ṭibb al-Nabawī (Prophetic medicine):* *No Qurʾānic or hadith provenance.* A. archangelica is not mentioned in the Qurʾān, the canonical hadith collections, the Prophetic-medicine compendia of Ibn Qayyim al-Jawziyya (_al-Ṭibb al-Nabawī_), or al-Suyūṭī (_al-Manhaj al-Sawī_). This is unsurprising — the herb's range is northern European and lies outside the geographical-historical reach of the Prophetic tradition — but worth flagging explicitly. The folk Arabic naming "_ḥabbat al-malāʾika_" (seed of the angels) is a *European naming-calque*, not a Prophetic attestation.#footnote[Verified absence: Ibn Sīnā, _al-Qānūn fī al-Ṭibb_, Book II (the survey of simple drugs in the canonical Beirut Dar al-Kutub al-ʿIlmiyya edition) does not have a _Hadhihi al-Adwiya / Anjlīkā_ entry; Ibn al-Bayṭār, _al-Jāmiʿ_, similarly lacks the herb. Modern Unani: AYUSH Ministry of India, _National Formulary of Unani Medicine_, _Hakim Mohammad Kabīruddīn, Bayāz-e Kabīr_; CCRUM publications — A. archangelica appears as a modern listed simple. Ibn Qayyim al-Jawziyya, _al-Ṭibb al-Nabawī_ (Cairo editions); al-Suyūṭī, _al-Manhaj al-Sawī_ — no entry. The "_ḥabbat al-malāʾika_" naming is a Latin → Arabic translation calque, post-classical.]

== Classical Formulas & Preparations

=== Chinese medicine (中醫)

*No classical Chinese formulas use A. archangelica.* The classical Chinese Angelica formulas use the three Chinese species (each is a separate canonical entry):

- *四物湯 (Sì Wù Tāng, "Four Substances Decoction")* — the foundational blood-tonic formula: 當歸 + 川芎 + 白芍 + 熟地黃. The cornerstone women's-medicine formula, from _Tài Píng Huì Mín Hé Jì Jú Fāng_ (12th c.).
- *當歸補血湯 (Dāng Guī Bǔ Xuè Tāng, "Dāng Guī Tonify-Blood Decoction")* — 黃芪 : 當歸 in a 5:1 ratio, for severe qi-blood vacuity (Li Dongyuan, _Nèi Wài Shāng Biàn Huò Lùn_).
- *當歸四逆湯 (Dāng Guī Sì Nì Tāng)* — for cold-pattern peripheral vascular insufficiency / Raynaud-type presentations (Zhāng Zhòngjǐng, _Shānghán Lùn_).
- *獨活寄生湯 (Dúhuó Jì Shēng Tāng)* — the canonical lower-body wind-damp _bi_ formula: 獨活 + 桑寄生 + others (Sūn Sī Miǎo, _Bèijí Qiānjīn Yào Fāng_).
- *川芎茶調散 (Chuānxiōng Chá Tiáo Sǎn)* — for headache patterns; 白芷 contributes the Yangming-channel reach (_Tài Píng Huì Mín Hé Jì Jú Fāng_).

For *A. archangelica* itself, modern Chinese herbal teas and digestive infusions occasionally include it as a Western-stomachic borrowing; no classical 本草 formula uses it.#footnote[Chinese Angelica formula sources: Bensky & Barolet, _Chinese Herbal Medicine: Formulas & Strategies_, 2nd ed. (Eastland Press, 2009). The clear non-substitution of A. archangelica for any of the Chinese Angelicas is standard materia-medica orthodoxy.]

=== Ayurveda

*No classical Sanskrit formulas use A. archangelica.* Modern Ayurvedic pharmacy (post-19th-century introduction):
- *_Choraka cūrṇa_* and *_choraka_-containing compounds* — if the _coraka_ = Angelica glauca identification is accepted, the *Himalayan species* (not the European) is the dravya used; the AYUSH National Formulary of Ayurvedic Medicine lists choraka in several digestive and respiratory cūrṇas. These do not transfer cleanly to A. archangelica.
- *Modern Indian Ayurvedic herbal teas and digestive churnas* sometimes include European angelica as an extension dīpana-pācana herb, by analogy with the canonical warming carminatives — *post-classical, not formulary*.#footnote[Choraka in the AYUSH _Ayurvedic Formulary of India_: a recognized listed dravya (with the species identification varying by edition); A. archangelica entries in modern Ayurvedic compendia are post-classical extensions — flagged.]

=== Western / Greco-Roman and later European medicine

*The richest tradition for this herb — and the only one in which A. archangelica is a primary canonical drug.*

- *Greco-Roman caveat:* A. archangelica is *not* a Mediterranean herb — its native range is northern European. Dioscorides (_De Materia Medica_) and Pliny (_Naturalis Historia_) do not treat A. archangelica directly; Galen mentions an _angelica_ but the species identification is uncertain and possibly refers to a southern Apiaceae (Levisticum or Smyrnium). The herb enters Western medicine as a *northern indigenous tradition* that is later synthesized into Galenic-humoral practice from the medieval period onward.
- *Sami / Old Norse / Icelandic:* the oldest documented European use of angelica. Pre-Christian Sami medical tradition treats *boska* / angelica as a sacred plant — chewed root and stem for digestion and strength, and as an antiscorbutic (the stems' modest vitamin-C content supplemented by the carminative-warming action); ash and decoction for respiratory and bone-pain complaints. Old Norse and Icelandic agricultural use of *hvönn* is the most complete pre-medieval Northern European medicinal-plant tradition; the *Grágás* law-code regulates communal harvesting.
- *Medieval European (post-13th c.):* A. archangelica becomes the canonical *plague remedy* of central European pharmacy. The legend of its origin — an archangel revealing the herb to a monk during plague (variously located to Magdeburg, Bavaria, or other central European houses) — circulates in many variant forms and is preserved by *Mattioli* (Pier Andrea Mattioli, _Commentarii in libros sex Pedacii Dioscoridis_, 1554), the major Italian Renaissance herbalist, whose extensive entry on _angelica_ is one of the principal medieval-modern transitions for the herb.
- *Paracelsus* (16th c.) classes angelica with the noble plague-remedies; *Hieronymus Bock* (_Kreutterbuch_, 1539) and the German Renaissance herbalists give it major treatment.
- *Hildegard von Bingen* — interestingly, _Physica_ (12th c.) does not have a dedicated angelica entry comparable to her treatment of fennel, suggesting the herb's central European reception is a *later* synthesis than Hildegard's German monastic pharmacy. Mattioli is the convincing first major Latin authority.
- *Carmelite Water* (*Eau de Mélisse des Carmes*, early 17th c.) — Discalced Carmelites of the rue de Vaugirard, Paris, developed this *melissa + angelica + nutmeg + lemon-peel + coriander + clove + cinnamon* distillate. Sold for centuries as a digestive, anti-syncope, and "stimulant" tonic, it persists in French pharmacy and apothecary tradition today and is the canonical European angelica preparation.
- *Bénédictine* (1863, Fécamp; reportedly based on an older Bénédictine monastic recipe), *Chartreuse* (Grande Chartreuse, Carthusian, distilled continuously since the early 17th c.) — angelica root is a *signature ingredient* in both. The Chartreuse formula is famously secret and reported to contain ~130 botanicals; angelica is among the publicly known ones.
- *Vermouth and gin:* angelica root is a *canonical bittering aromatic* in vermouth and (with juniper and coriander) in gin — for many modern Europeans the herb's flavor profile is more familiar from these spirits than from any direct medicinal preparation.
- *Crystallized angelica stems:* a longstanding European confectionery — angelica stems candied in syrup, used as garnish on cakes (classic French gâteau and Italian _candita_ tradition). *Niort* in western France (Deux-Sèvres) was historically the European center of crystallized-angelica production from the 17th–19th c.
- *Modern Western herbal:* digestive bitters, cough syrups (Iceland, the Faroes, and Norway preserve the strongest traditional respiratory use), respiratory aromatic, mild anxiolytic / sedative reputation. *ESCOP* and *Commission E* list _Angelicae radix_ for dyspepsia and as a digestive aromatic. The modern Western herbal register is the *clinically continuous* tradition for the herb.#footnote[Greco-Roman caveat: Dioscorides, _De Materia Medica_; Pliny, _Naturalis Historia_; Galen — A. archangelica is not the primary referent of classical Mediterranean _angelica_ where the word appears at all. Mattioli, _Commentarii_, 1554 — extensive angelica entry. Hieronymus Bock, _Kreutterbuch_, 1539. Sami / Norse / Icelandic tradition: ethnobotany sources cited above. Carmelite Water: Couleau, _Le Carmel de Paris_, and standard French pharmaceutical histories. Chartreuse / Bénédictine: standard monastic-liqueur historiography. Niort crystallized angelica: standard French regional gastronomy. ESCOP _Monographs_, _Angelicae radix_; Commission E.]

=== Ṭibb (Arabic-Islamic medicine)

As established in the Tibb section above: A. archangelica is *not* in the classical Avicennan / al-Bayṭār / Maghrebi-Andalusian corpus. Modern Unani pharmacy under AYUSH lists the herb as an imported deobstruent-carminative; classical Tibb formulas do not include it. Modern Unani compound preparations occasionally use angelica as a *post-classical extension* on the warm-dry umbellifer axis — by analogy with anīsūn, rāziyānaj, karawiyā, kammūn — in 19th–20th-century digestive _sharbat_ and _maʿjūn_ syntheses. No pre-modern Tibb _murakkabāt_ are built around A. archangelica.

== Climate, Constitution & Regional Diet

A. archangelica is a *cold-climate plant*, native to the cool-damp temperate Atlantic and cold-damp boreal / subarctic zones of northern Europe — Iceland, the Faroes, coastal Norway, Lapland and northern Sweden, parts of Russia, and the Scottish and northern English highlands. The plant tolerates extreme cold and short summers and does *not* thrive in warm-dry Mediterranean or hot-humid tropical conditions. Its medicinal profile — *warming, drying, aromatic, pungent-bitter, mood-elevating* — is a textbook climatic-constitutional corrective to the very climate in which it grows: the dravyaguna / 中醫 / Tibb / Galenic readings all converge on this. See `climates.typ` for the foundational framework (the cool-damp Atlantic and cold-damp boreal / subarctic zones).

=== Cold-damp boreal / subarctic (Sami, Norse, Icelandic, Faroese, Northern Russian) — the native climate

Cold, damp, dark winters; brief intense summers; strong wind from the North Atlantic and Arctic. The constitutional pressure is _kapha-vāta-vardhaka_ in dravyaguna (Kapha from chronic damp and snow; Vāta from cold-dry winter wind and long darkness), 寒濕 + 腎陽虛 (cold-damp + chronic Kidney-yang vacuity) in 中醫, and phlegmatic-and-melancholic in Galenic humoral.

*Traditional preparation.* The Sami pre-Christian tradition chews fresh _boska_ root and stem for digestion, vigour, and as an antiscorbutic; smokes the leaves; uses decoctions for respiratory complaints and articular pain. The Old Norse / Icelandic tradition treats _hvönn_ as a regulated communal resource (per the *Grágás*), with the stems consumed as a vegetable, the root used medicinally, and the seeds for culinary aromatic and digestive use. The Norwegian *kvann* tradition is continuous to the present: cultivated in highland farms, used in cough syrups, included in the canonical *kvannepulver* (angelica powder) for stomach complaints, and incorporated into *akvavit* (the caraway-and-angelica distilled spirit, the canonical Scandinavian apéritif and digestif). The Icelandic *hvönn* root remains a national medicinal plant with both folk and commercial register.

*Cares.* The cold-damp climate is exactly the climate angelica is constitutionally suited to: warming, drying, aromatic, dispels cold and damp from the chest and joints, supports Kidney-yang. The classical Norse-Sami use is the textbook *climatically appropriate* preparation: chewed warm, drunk warm, distilled into spirits, used as a fortifying smoke. *Cold or iced preparations of angelica in this climate would invert the classical-constitutional logic* — the warming intensity of the herb is constitutive, and chilling it forfeits the corrective action it was selected for. Akvavit served *room-temperature* or slightly chilled (Scandinavian custom) is on the warming side; akvavit served deeply frozen (the modern Nordic custom of freezing the bottle) is a stylistic-modern departure that the classical reading would flag as climatically uneconomic.

=== Cool-damp temperate Atlantic (Britain, Ireland, central / northern Europe) — secondary native and traditional range

Cool, damp, low-sun, wind-exposed: Vāta-Kapha; 寒濕; phlegmatic. A. archangelica enters central European pharmacy in the medieval period and the *plague-remedy* register is the canonical traditional use; the herb is also incorporated into the great monastic-distillate tradition (*Carmelite Water*, *Chartreuse*, *Bénédictine*), the British gin and vermouth tradition, the French Niort crystallized-stem confectionery, and the modern Western herbal-tea and digestive-bitters register. All are *climatically apt* applications of a warm-dry aromatic in cool-damp territory.

*Cares.* In central Europe, the warming-and-distilled register is the canonical one; the *fermentation / distillation* route is a _saṃskāra_-class warming correction (raw cool aromatic → finished warming spirit), paralleling the barley → whisky / beer inversion. Cold raw infusions or chilled aromatic waters are climatically uneconomic for cool-damp Atlantic regimens — the traditional pharmacy preserves the warming register.

=== Climates where A. archangelica is not traditional (Mediterranean warm-dry, hot-humid tropical, high altitude)

A. archangelica is *not* a classical Mediterranean, Middle Eastern, or tropical herb. Its post-medieval introduction into Mediterranean monastic pharmacy and into modern Tibb is a *non-native extension*. In hot-dry Mediterranean climates the herb's Hot-Dry Tibb mizāj and uṣṇa-tīkṣṇa Ayurvedic profile makes it Pitta-aggravating and unsuitable for chronic dietary use; in hot-humid tropical climates the warming-drying profile is climatically inappropriate as a primary tonic. *Cares (by extension, not classical):* restrict to small medicinal doses in cool months, combine with cooling adjuvants (rose-water, mint, lime, sharbat-sugar), avoid heavy or chronic use, prefer the canonical cooler-climate umbellifers (rāziyānaj, anīsūn, kammūn, kishnīz) for the warm-climate carminative niche.

=== Modern transposition (_deśa-viruddha_)

The modern globalized aperitivo / digestif culture moves warming aromatic bitters — vermouth, Chartreuse, gin — across climates without seasonal adjustment: angelica-based liqueurs taken on ice in Bangkok in May, vermouth-on-the-rocks in São Paulo. The classical reading would treat these as _deśa-viruddha_ (place-incompatible) preparations: the warming-drying corrective for a cold-damp Atlantic body is no longer doing the constitutional work it was selected for, and the heat-amplifying effect on a Pitta-loaded summer body is the precise inversion of the original intent. The traditional climatically-apt register is *warm preparations in cold-damp climates*. Recognizing the category — and naming it explicitly — keeps the modern use tractable: a chilled angelica liqueur in the tropics is enjoyable but not corrective; the classical reading is honest about this. See Caraka Sū. 26 for the _viruddha_ framework; see `climates.typ` for the cool-damp Atlantic and cold-damp boreal climate profiles.#footnote[The cool-damp Atlantic and cold-damp boreal / subarctic climate readings: see `climates.typ`. Sami / Norse / Icelandic ethnobotany: Høeg, _Planter og Tradisjon_; Svanberg, Sami ethnobotany literature. Norwegian kvann tradition: standard Nordic ethnobotanical literature. Akvavit composition (caraway as primary, angelica as secondary; varies by producer): standard spirits-history sources.]

== Modern Nutrition & Pharmacology

*Key constituents (dried root):*
- *Essential oil (0.3–1.5%):* β-phellandrene (major), α-pinene, sabinene, δ-3-carene, α-phellandrene, limonene, p-cymene, myrcene, copaene; sesquiterpenes (β-caryophyllene, β-bisabolene). The aroma is characteristic: sharp, resinous, warm-aromatic, with musk and earthy notes — recognizable in Chartreuse and gin.
- *Furanocoumarins (key — phototoxic):* bergapten (5-MOP), xanthotoxin (8-MOP), imperatorin, phellopterin, isoimperatorin, angelicin, oxypeucedanin, marmesin. *The photosensitizing fraction* — the source of phytophotodermatitis on skin contact + sun exposure.
- *Simple coumarins:* umbelliferone, scopoletin, osthol.
- *Phenolic acids and lignans:* chlorogenic acid, caffeic acid, ferulic acid; sesamin.
- *Polysaccharides* in the root: mild immunomodulatory in vitro.
- *Fatty acids, resins, sterols (β-sitosterol).*#footnote[Phytochemistry: standard pharmacognosy (Evans, _Trease and Evans' Pharmacognosy_); ESCOP _Monographs_, _Angelicae radix_; reviews in _Phytochemistry_, _Journal of Ethnopharmacology_, _Phytochemistry Reviews_. The furanocoumarin profile is the key safety-relevant chemical feature.]

*Pharmacology of note:*
- *Carminative and antispasmodic:* the essential oil has documented antispasmodic activity on intestinal smooth muscle (preclinical), supporting the cross-system convergent classical use. Clinical evidence in functional dyspepsia: modest, generally favorable.
- *Cholagogue / digestive bitter:* bitter coumarin and furanocoumarin fraction stimulates bile flow; the pharmacological basis of the angelica-in-bitters tradition.
- *Anti-inflammatory:* coumarins (osthol particularly) and sesquiterpenes show anti-inflammatory activity preclinically; clinical evidence modest.
- *Antimicrobial:* essential oil shows in vitro activity against Gram-positive bacteria, mycobacteria, and Candida; historically aligned with the plague-remedy reputation, though direct clinical translation is modest.
- *Sedative / anxiolytic:* mild; some preclinical and limited clinical support; the modern "angelica calming bitters" tradition has phytopharmacological plausibility, esp. via GABA-system effects of certain coumarins.
- *Photosensitization (phytophotodermatitis):* furanocoumarins (esp. bergapten and 8-MOP) cause sun-activated skin reactions — *the signature modern caution*, particularly for topical use and high-dose internal use combined with sun exposure. The mechanism is shared with bergamot, lime, giant hogweed, and parsnip.
- *CYP3A4 inhibition (in vitro):* bergapten and imperatorin inhibit cytochrome P450 3A4; potential drug interaction with CYP3A4-metabolized medications. Clinical relevance modest at dietary / typical-herbal doses but worth flagging — the mechanism is shared with grapefruit furanocoumarins (the "grapefruit interaction" of pharmacology).
- *Mild blood-sugar lowering:* preclinical; combine cautiously with antidiabetic medication.
- *Mild estrogenic activity:* preclinical; relevance to the classical emmenagogue use and to estrogen-sensitive contexts; the activity is modest compared to soy or red clover.

*Safe daily dosage / upper limit:*
- *ESCOP / Commission E monograph (Angelicae radix), dyspepsia:* 1–3 g dried root per day (as infusion); tincture 1.5–3 mL of 1:5 tincture three times daily; essential oil 0.05–0.3 g per day, typically in compound preparation.
- *Culinary register (crystallized angelica, vermouth, gin, Chartreuse-style liqueurs):* small dietary quantities — no toxicological concern at normal consumption levels.
- *Topical use:* *avoid sun exposure for 24–48 hours* after topical application — phytophotodermatitis risk.
- *Pregnancy:* avoid therapeutic doses (emmenagogue, uterine-stimulant); culinary-register quantities (small amounts in food, vermouth, liqueurs) are generally considered safe.
- *Concurrent medication:* anticoagulants (theoretical interaction, monitor INR if warfarin-treated); antidiabetics (theoretical, monitor blood glucose); CYP3A4-metabolized drugs (theoretical, modest concern at typical doses).
- *Apiaceae allergy:* cross-reactivity within the family.
- *Wild-harvesting:* the *hemlock confusion* is the single most important practical safety point — A. archangelica resembles *_Cicuta virosa_* (water hemlock — among the most poisonous plants in the temperate flora) and *_Conium maculatum_* (poison hemlock — Socrates' executioner). Wild-harvested angelica requires reliable expert field identification; the standard diagnostic features (stem markings, root aroma, umbel shape, habitat) must be checked together. The classical Northern European foraging tradition is exact about this — the *kvann* / *hvönn* / *boska* harvest is a transmitted, supervised skill.
- *Reference figures, not personalized medical advice.* For pharmacological dose use, clinician supervision is warranted, particularly in pregnancy, photosensitization risk, anticoagulant contexts, and concurrent CYP3A4-metabolized medication.#footnote[Dose ranges: ESCOP _Monographs_, _Angelicae radix_; Commission E monograph; WHO _Monographs on Selected Medicinal Plants_ where indexed. Phototoxicity from furanocoumarins: standard dermatology and pharmacognosy literature; the mechanism is shared with bergamot, lime, parsnip, and giant hogweed. CYP3A4 inhibition in vitro: peer-reviewed phytopharmacology; clinical relevance modest at typical doses. The hemlock identification caveat is universal in wild-harvesting literature — verify against current ethnobotanical / field-identification sources before any wild harvest.]

== Sources

- _Bencao Gangmu_ (本草綱目), 1578 — 當歸, 白芷, 獨活 entries (the three canonical Chinese Angelicas; the European A. archangelica is *not* a 本草 drug); Bensky, Clavey & Stöger, _Chinese Herbal Medicine: Materia Medica_, 3rd ed. (Eastland Press, 2004); Bensky & Barolet, _Chinese Herbal Medicine: Formulas & Strategies_, 2nd ed. (Eastland Press, 2009).
- Caraka Saṃhitā, Sūtrasthāna 26 (_viruddha_) — Sharma & Dash (Chowkhamba); cited only for the viruddha framework applied here by extension; A. archangelica has *no classical Indian entry*.
- P. V. Sharma, _Dravyaguṇa-vijñāna_, vol. II — _coraka_ identification debate (Angelica glauca vs. other Himalayan umbellifers); AYUSH Ministry of India, _Ayurvedic Formulary of India_ — _coraka_ entries (modern).
- Ibn Sīnā, _al-Qānūn fī al-Ṭibb_, Book II (_al-Adwiya al-Mufrada_) — verified: A. archangelica *not present* in classical entries; Ibn al-Bayṭār, _Kitāb al-Jāmiʿ li-Mufradāt al-Adwiya wa-l-Aghdhiya_ — *not present*; al-Rāzī, _al-Ḥāwī_ — *not present*. AYUSH Ministry of India, _National Formulary of Unani Medicine_; Hakim Mohammad Kabīruddīn, _Bayāz-e Kabīr_; CCRUM publications — modern Unani A. archangelica listings (post-classical extension).
- Ibn Qayyim al-Jawziyya, _al-Ṭibb al-Nabawī_; al-Suyūṭī, _al-Manhaj al-Sawī_ — verified: no entry, no Qurʾānic / hadith provenance.
- Dioscorides, _De Materia Medica_; Pliny, _Naturalis Historia_; Galen, _On the Properties of Foodstuffs_ — A. archangelica *not* the primary referent of classical Mediterranean _angelica_; the herb's Western canonical status begins in the medieval period.
- Hieronymus Bock, _Kreutterbuch_ (1539); Mattioli, _Commentarii in libros sex Pedacii Dioscoridis_ (1554) — the major Renaissance angelica entries; Paracelsus on angelica; Hildegard, _Physica_ (note: Hildegard does *not* have a dedicated angelica entry comparable to her fennel treatment).
- _Grágás_, the medieval Icelandic law-code (12th–13th c.) — communal _hvönn_ harvesting regulation; Dennis, Foote, & Perkins, _Laws of Early Iceland: Grágás_ (translation).
- Høeg, _Planter og Tradisjon_ (Norwegian ethnobotany, mid-20th c.); Svanberg on Sami ethnobotany; Kallio on Finnish/Sami plant use — for the Nordic / Sami / Icelandic indigenous angelica tradition.
- ESCOP _Monographs_, _Angelicae radix_; Commission E monograph, _Angelicae radix_; WHO _Monographs on Selected Medicinal Plants_ where indexed; Evans, _Trease and Evans' Pharmacognosy_; current reviews in _Phytotherapy Research_, _Phytomedicine_, _Journal of Ethnopharmacology_.
- Couleau, _Le Carmel de Paris_ (Carmelite Water historiography); standard monastic-liqueur historiography (Bénédictine, Chartreuse); standard French regional gastronomy (Niort crystallized angelica).
- Climate framework: see `climates.typ`. Tibb framework: see `tibb-al-arabi.typ`.
- Lewis & Short, _A Latin Dictionary_; _Oxford English Dictionary_; Marzell, _Wörterbuch der deutschen Pflanzennamen_; Monier-Williams, _A Sanskrit–English Dictionary_; _Hanyu Da Cidian_ (漢語大詞典).
- See related Chinese-Angelica entries (to be added): 當歸 (dāngguī, _A. sinensis_); 白芷 (báizhǐ, _A. dahurica_); 獨活 (dúhuó, _A. pubescens_).
