= Korean Ginseng (인삼 / 人參)

_Scope: this entry treats *Panax ginseng* C.A. Meyer (Araliaceae) — the Chinese 人參 (rénshēn) and Korean 인삼 (insam) — and above all its *processing-derived drug-forms*, which this tradition elaborates as fully as Chinese pharmacy elaborates ginger: *수삼 (susam,* fresh), *백삼 (baeksam,* white, peeled and sun-dried), *홍삼 (hongsam,* red, steamed then dried — the signature Korean product), *흑삼 (heuksam,* black, repeatedly steamed), with wild *산삼 (sansam)* as a class apart. The drug is the root. Status: *deeply classical in Chinese medicine* — _Shennong Bencao Jing_ 上品, and the archetype of the entire 補氣 (qi-tonifying) category — and *the single most culturally and economically central medicinal plant of Korea*, with its own classical textual tradition (the _Donguibogam_, 1613) that this entry treats alongside the Chinese. Not classical in Ayurveda, Tibb, or Greco-Roman medicine; those sections are reasoned extension, flagged. Four disambiguations are load-bearing: (1) "Indian ginseng" is *ashwagandha* (_Withania somnifera_), an unrelated Solanaceae — see ashwagandha.typ; (2) "Siberian ginseng" is *eleuthero* (_Eleutherococcus senticosus_), not a Panax at all; (3) American ginseng (_P. quinquefolius_, 西洋參) and notoginseng (_P. notoginseng_, 三七) are *separate drugs with opposite thermal properties*, deserving their own entries; (4) the Chinese character 參 is a *root-drug suffix*, not the word "ginseng" — 黨參, 丹參, 玄參, 苦參 are unrelated drugs._

== Nomenclature & Etymology

*Latin / botanical:* *_Panax ginseng_ C.A. Meyer* (1843), family Araliaceae; the drug is the *dried root* (_Ginseng radix_, Korean Pharmacopoeia _Ginseng Radix Rubra_ for red ginseng). The genus *_Panax_* was established by Linnaeus (1753) from Greek *πάναξ (pánax)* / *πανάκεια (panákeia)* — *πᾶν (pân,* "all") + *ἄκος (ákos,* "cure, remedy") — "all-healing," the same root that gives English *panacea*; *Panákeia* was in myth a daughter of Asclepius and the goddess of universal remedy. *Note the contrast with this book's other Greek-named East Asian plants:* where _Coix_, _Chrysanthemum_, and _Lycium_ are *false friends* (classical plant-names misapplied to unrelated Asian species — see `coix.typ`, `chrysanthemum.typ`, `goji-berry.typ`), *Panax* is a *deliberate descriptive coinage* — Linnaeus was not transferring an ancient plant-name but asserting the drug's reputation. The name is therefore apt rather than accidental, though "panacea" is of course a claim this book does not endorse.#footnote[Etymology: Liddell & Scott, _A Greek–English Lexicon_ (s.v. πάναξ, πανάκεια, ἄκος); Linnaeus, _Species Plantarum_ (1753), establishing _Panax_ on the American species _P. quinquefolius_; _P. ginseng_ was described by C.A. Meyer in 1843. Note that Linnaeus's _Panax_ was founded on the *American* plant, the Asian species being formally named ninety years later — a consequence of the Jesuit-mediated discovery sequence described below. Panákeia as daughter of Asclepius: standard classical mythography; cf. the Mintha myth in `mint.typ` for the other mythologically-anchored plant name in this book.]

*Chinese:* *人參 / 人参 (rénshēn)* — *人* ("human") + *參* (the root-drug character). The name records the *anthropomorphic forked root*: a well-grown ginseng root has a head, a body, and two or more leg-like branches, and the classical literature is explicit that the most man-shaped roots were the most valued. This is a *genuine classical etymology*, discussed in the Bencao tradition, not a modern folk gloss — though the valuation it expresses is a *doctrine-of-signatures* reasoning rather than a pharmacological one, and should be read as such.#footnote[人參 in _Shennong Bencao Jing_ (神農本草經), 上品 (superior grade); the man-shaped-root etymology and the valuation of anthropomorphic roots are discussed by Li Shizhen, _Bencao Gangmu_ (本草綱目), 1578, 人參 entry, and are standard throughout the Bencao tradition. Flagged as doctrine-of-signatures reasoning: the root's shape is a grading criterion in the tradition, not a pharmacological variable.]

*A cross-cultural parallel, flagged as parallel and not connection:* the European *mandrake* (_Mandragora officinarum_) is the other great *anthropomorphic forked root* of Old-World pharmacy, likewise credited with extraordinary power and surrounded by harvest taboos and ritual. The convergence — two unrelated traditions investing a man-shaped root with maximal potency — is a striking instance of signature-reasoning arising independently; there is *no historical connection* between the two drugs, and mandrake (a tropane-alkaloid-bearing Solanaceae) is genuinely dangerous where ginseng is not.

*The 參 caution — a disambiguation this book needs:* *參 (shēn)* is a *suffix for tonic-and-medicinal roots*, not a word meaning "ginseng." Drugs sharing it are frequently *unrelated*:
- *黨參 (dǎngshēn)* — _Codonopsis pilosula_ (Campanulaceae); a *milder, cheaper qi tonic* used as ginseng's standard substitute at larger dose, lacking the 大補元氣 emergency action.
- *西洋參 (xīyángshēn, "Western-ocean ginseng")* — *American ginseng*, _P. quinquefolius_; *same genus, opposite thermal property* — cool (涼) and yin-fluid-tonifying where Korean ginseng is slightly warm and qi-tonifying. The two are *not interchangeable*, and the distinction is clinically consequential (see the Climate section for how markets express it).
- *三七 / 田七 (sānqī / tiánqī)* — _P. notoginseng_; same genus, but a *blood-moving and bleeding-stopping* drug, functionally remote from ginseng.
- *太子參 (tàizǐshēn)* — _Pseudostellaria heterophylla_; a gentle qi-and-yin tonic for children and the frail.
- *丹參 (dānshēn)* — _Salvia miltiorrhiza_ root, a blood-invigorator (see `sage.typ`); *玄參 (xuánshēn)* — _Scrophularia_; *苦參 (kǔshēn)* — _Sophora flavescens_, a bitter-cold damp-heat drug. *None of these is a ginseng.*

*Korean:* *인삼 (insam)* = 人蔘; and in its national designation *고려인삼 (Goryeo insam, "Goryeo ginseng")* — after the *Goryeo* dynasty (918–1392), the same dynastic name from which "Korea" itself derives, so that the plant and the country share an etymology. Korea's claim on this plant is not merely commercial: *고려인삼* is treated as a national patrimony, and _P. ginseng_ of Korean origin commands a distinct premium in East Asian markets.

*Korean cultivation and processing vocabulary — the heart of this entry:*
- *수삼 (susam, 水蔘, "water ginseng")* — *fresh* undried root; perishable, used in cooking and fresh preparations.
- *백삼 (baeksam, 白蔘, "white ginseng")* — peeled and *sun-dried*; the lighter, more neutral drug.
- *홍삼 (hongsam, 紅蔘, "red ginseng")* — *steamed with skin on, then dried*; the root turns reddish-amber and horn-hard, keeps for years, and is read as *warmer and more strongly tonifying* than white. *The signature Korean product*, and the form in which Korean ginseng is overwhelmingly exported. Modern phytochemistry has vindicated the distinction in detail (see Modern Pharmacology) — this is a *saṃskāra* transformation on a par with 生薑/乾薑 ginger and 生地/熟地 rehmannia (see `ginger.typ`, `rehmannia.typ`).
- *흑삼 (heuksam, 黑蔘, "black ginseng")* — *repeatedly steamed and dried* (classically nine cycles, the same 九蒸九晒 logic as rehmannia); darker, with a further-transformed ginsenoside profile. Largely a modern commercial elaboration of a classical procedure.
- *태극삼 (taegeuksam, 太極蔘)* — briefly scalded before drying; intermediate between white and red.
- *산삼 (sansam, 山蔘, "mountain ginseng")* — *wild* ginseng; a class apart, extraordinarily expensive, and surrounded by a living folk culture: the *심마니 (simmani)*, wild-ginseng gatherers, observe ritual preparation, taboo, and a specialized vocabulary, and call out *"심봤다!" (simbwatda,* "I've found ginseng!") on a discovery. *장뇌삼 (jangnoesam)* — semi-wild ginseng, sown and left in mountain forest, intermediate in status and price.
- *Production centres:* historically *개성 (Gaeseong)* — now in North Korea — and today *금산 (Geumsan)*, *강화 (Ganghwa)*, *풍기 (Punggi)*. *정관장 (Jung Kwan Jang)* is the principal modern brand, descending institutionally from a state ginseng monopoly.

*Chinese drug-forms (parallel but not identical vocabulary):* *生曬參 (shēngshàishēn,* sun-dried), *紅參 (hóngshēn,* red), *糖參/白參* (sugar-processed/white), *人參鬚 (rénshēnxū,* the fine rootlets — a weaker, much cheaper drug), *蘆頭 (lútóu,* the rhizome neck — *classically removed before use, being held emetic*), *野山參 (yěshānshēn,* wild), *林下參 (línxiàshēn,* forest-grown). Premium Chinese origin: *吉林 (Jilin)* and the *長白山 (Changbai Shan)* range — the same mountain system Koreans call *백두산 (Baekdusan)*.

*Japanese:* *朝鮮人参 (chōsen ninjin)* / *高麗人参 (kōrai ninjin)*; red ginseng *紅参 (kōjin)*. *A necessary caution:* in modern Japanese, *人参 (ninjin)* alone means *carrot* — the word was transferred to the European root vegetable on the strength of a shape resemblance, so Japanese *requires* the qualifier 朝鮮/高麗 to mean ginseng. A Japanese recipe calling for 人参 wants carrots.

*Sanskrit:* *no classical name* — _P. ginseng_ is a Northeast Asian understory perennial with no entry in Caraka, Suśruta, or the nighaṇṭus. *The critical disambiguation:* the popular Western name *"Indian ginseng"* denotes *अश्वगन्धा (aśvagandhā)*, _Withania somnifera_ — an unrelated Solanaceae with its own substantial classical standing as a _rasāyana_ and _vājīkaraṇa_ drug. See `ashwagandha.typ`, which flags the misnomer from the other side. The two plants are botanically unrelated and *phytochemically distinct* (withanolides vs. ginsenosides); what they genuinely share is a *functional category* — tonic, restorative, stress-buffering, aphrodisiac-adjacent — which is why the analogy was drawn, and why it is misleading as botany while being intelligible as pharmacology. Modern Indian markets sell Panax under the English name; there is no classical Sanskrit lemma, and modern Sanskritizing coinages should not be presented as one.

*Arabic / Persian / Urdu:* *جنسنج / جينسنغ (jinsinj / jīnsinġ)* — *modern transliterations*, not classical drug-names. _P. ginseng_ is *absent from Avicenna's Qānūn and Ibn al-Bayṭār's al-Jāmiʿ*; see the Tibb section. Modern Unani practice in South Asia has adopted it as a post-classical tonic.

*English:* *ginseng*, from Chinese 人參, most likely via a *southern Chinese dialectal pronunciation* transmitted through the 17th-c. Canton and Jesuit channels; the precise route is debated and the OED's account should be consulted rather than paraphrased confidently.#footnote[_Oxford English Dictionary_ (s.v. "ginseng, n.") — borrowing from Chinese 人參 via a southern dialectal form, with the transmission route not fully settled; flagged rather than asserted. The 17th–18th-c. European reception is treated in the Western section below.]

== Classical Chinese Medicine (中醫) View

人參 is *the archetypal drug of the 補氣 (qi-tonifying) category* — a _Shennong Bencao Jing_ 上品 drug, the sovereign herb of the foundational qi-tonic formulas, and the one drug classical Chinese medicine reaches for when life itself is ebbing.

*Property (性 xìng):* Slightly warm (微溫). *Form-dependent:* *紅參* (red) is read as *warmer*, more yang-supporting; *生曬參/白參* as nearer neutral; and *西洋參* (American) as frankly *cool* — one genus, three thermal placements, assigned by species and processing.

*Flavor (味 wèi):* Sweet (甘), slightly bitter (微苦).

*Channels (歸經 guījīng):* Spleen (脾), Lung (肺), Heart (心); Kidney (腎) in many modern sources.

*Actions and indications:*
- *大補元氣 (dà bǔ yuán qì, "greatly tonifies the source qi")* — *the signature action, and unique in its degree.* For *氣虛欲脫* (qi vacuity verging on collapse): shortness of breath, profuse cold sweat, cold limbs, a *pulse faint and on the verge of expiring* (脈微欲絕). The classical expression of this is *獨參湯 (Dú Shēn Tāng,* "Ginseng Alone Decoction") — *ginseng as a single drug in large dose*, given in catastrophic collapse, massive haemorrhage, and postpartum exsanguination. That the tradition reserves a *single-herb* formula for its gravest emergencies, and that the herb chosen is this one, is the clearest statement of ginseng's standing in the pharmacy.
- *補脾益肺 (bǔ pí yì fèi)* — tonifies Spleen and augments Lung qi: poor appetite, loose stools, fatigue, shortness of breath, weak voice, spontaneous sweating. The foundational formulas are *四君子湯 (Sì Jūnzǐ Tāng)* — ginseng as sovereign with 白朮, 茯苓, 炙甘草 (see `fuling.typ`) — and *補中益氣湯 (Bǔ Zhōng Yì Qì Tāng)*, Li Dongyuan's qi-raising formula (see `astragalus.typ`), together with *參苓白朮散*.
- *生津止渴 (shēng jīn zhǐ kě)* — generates fluids and allays thirst: for *暑傷氣* (summer-heat damaging qi) and for *消渴 (xiāokě)*, the classical consumptive-thirst category covering diabetic-spectrum disease. The formulas are *白虎加人參湯 (Bái Hǔ Jiā Rén Shēn Tāng,* White Tiger plus Ginseng, _Shāng Hán Lùn_) for high fever with fluid-and-qi damage, and *生脈散 (Shēng Mài Sǎn,* Generate-Pulse Powder) with 麥門冬 and 五味子 — see `schisandra.typ`.
- *安神益智 (ān shén yì zhì)* — calms the spirit and benefits the wits: palpitations, insomnia, poor memory, timorousness of qi-and-blood vacuity. In *歸脾湯* (see `fuling.typ`) and *天王補心丹*.
- *回陽救逆 support (huí yáng jiù nì)* — in yang-collapse formulas, ginseng is added to the aconite-and-dried-ginger core: *四逆加人參湯* (_Shāng Hán Lùn_) and *參附湯* (ginseng with aconite), the classical shock therapy — and the ancestor of the *參附注射液* injectable used in modern Chinese critical care.

*Comparison with the other great qi tonic.* Ginseng and *黃芪 (astragalus)* are the two principal qi tonics, and the contrast is textually sharp: ginseng acts on *元氣 (yuán qì,* source qi) and is reserved, expensive, and used in *small doses for acute, severe vacuity*; astragalus acts on *衛氣 (wèi qì,* defensive/surface qi), raises sinking yang, and is used in *large doses for chronic mild vacuity*. See `astragalus.typ` for the full comparison, which this entry does not duplicate.

*Cautions and classical incompatibilities — unusually specific for this drug:*
- *Contraindicated in excess-heat and repletion patterns* (實熱), in *陰虛火旺* (yin vacuity with flaring fire), in hypertension with Liver-yang rising, and in any acute exterior excess condition — the classical rule being that *tonifying an excess pattern reinforces the pathogen* (補其實, "supplementing what is already full").
- *人參反藜蘆* — ginseng *counteracts* 藜蘆 (_Veratrum_), one of the canonical *十八反 (shíbā fǎn,* eighteen antagonisms); the mnemonic verse runs *諸參辛芍叛藜蘆* ("all the shen, asarum, and peony rebel against Veratrum").
- *人參畏五靈脂* — ginseng *fears* 五靈脂 (_Trogopterus_ dung), among the *十九畏 (shíjiǔ wèi,* nineteen mutual fears) — the same incompatibility class in which clove fears turmeric (see `cloves.typ`).
- *蘆頭 (the rhizome neck) is traditionally removed*, being held emetic.
- *Folk rules, (F)-tier:* ginseng is traditionally not taken with *tea* or with *蘿蔔 (radish/daikon)*, both being held to *disperse qi* and so to undo the tonification. Widely observed in Chinese and Korean households; folk-dietetic rather than textual.#footnote[人參 in _Shennong Bencao Jing_ (上品); Li Shizhen, _Bencao Gangmu_ (1578). Formula sources: Zhang Zhongjing, _Shāng Hán Lùn_ (傷寒論) for 白虎加人參湯 and 四逆加人參湯; _Tài Píng Huì Mín Hé Jì Jú Fāng_ (1108) for 四君子湯; Li Dongyuan, _Pi Wei Lun_ (脾胃論, 12th c.) for 補中益氣湯 (as cited in `astragalus.typ`); Zhang Yuansu, _Yi Xue Qi Yuan_ (醫學啟源, 12th c.) for 生脈散 (as cited in `schisandra.typ`); Yan Yonghe, _濟生方_ (13th c.) for 歸脾湯 (as cited in `fuling.typ`). 獨參湯 is transmitted in later formularies and commonly attributed to Ge Qiansun's _Shí Yào Shén Shū_ (十藥神書, 14th c.) — attribution flagged for verification. The 十八反 and 十九畏 lists: standard Bencao-and-formula literature; Bensky, Clavey & Stöger, _Materia Medica_, 3rd ed.; Bensky & Barolet, _Formulas & Strategies_, 2nd ed.]

== Ayurvedic Dravyaguna (द्रव्यगुण)

_Reasoned analysis, not classical._ Panax ginseng _is a Northeast Asian plant with no entry in Caraka, Suśruta, or the nighaṇṭus, and no Sanskrit name (the "Indian ginseng" of popular usage is_ Withania somnifera _— see Nomenclature and `ashwagandha.typ`). The reading below applies dravyaguna principles by extension, in the register of the other reasoned-only East-Asian entries (`astragalus.typ`, `fuling.typ`). One observation makes this section more than an exercise: ginseng's classical Chinese profile maps with unusual precision onto a_ developed _Ayurvedic category — the_ rasāyana_-plus-_vājīkaraṇa _tonic — which is precisely why the "Indian ginseng" analogy was ever drawn._

*Reasoned rasa:* Madhura (मधुर, sweet — the dominant, and the rasa of all nourishing tonics), with Tikta (तिक्त, bitter) as *anurasa* (secondary taste) — matching the classical 甘微苦 attribution exactly.

*Reasoned guṇa:* Guru (गुरु, heavy — the nourishing, substantial quality of a tonic root), Snigdha (स्निग्ध, unctuous — mildly), Sūkṣma (सूक्ष्म, subtle — the penetration that lets it reach and restore the depleted _dhātu_).

*Reasoned vīrya:* Uṣṇa (उष्ण, heating — mildly), matching 微溫. *Form-sensitive, and the dravyaguna framework handles this well:* *홍삼/紅參* (red, steamed) reads as more frankly *uṣṇa*, the processing having intensified potency — a straightforward _agni-saṃskāra_ — while *백삼/白參* approaches *anuṣṇāśīta* (neutral) and American ginseng (西洋參) would read as *śīta*.

*Reasoned vipāka:* Madhura (मधुर, sweet).

*Prabhāva:* *None classically* — no classical entry exists. If one were singled out, the candidate is specific and strong: *the restoration of life in imminent collapse* — the 大補元氣 action of *獨參湯*, by which a single sweet, mildly warm, heavy root is given to a patient whose pulse is failing. In dravyaguna terms this is a *jīvanīya* (life-giving) and *prāṇa-and-ojas-restoring* action of a degree *not* predictable from madhura rasa, guru-snigdha guṇa, uṣṇa vīrya, and madhura vipāka — many drugs share those parameters and none of them is given alone in extremis. That is exactly the prabhāva criterion (Caraka Sū. 26.67–72). Flagged as *interpretive*: the reading is this book's, applied to a classical Chinese indication.

*Reasoned doṣa effect:* *Vāta-śāmaka* (the governing effect — madhura-guru-snigdha-uṣṇa is the canonical Vāta-pacifying combination, and Vāta-depletion is the dravyaguna analogue of qi vacuity); *Pitta-vardhaka* (uṣṇa — and note that this corresponds precisely to the classical Chinese contraindication in 實熱 and 陰虛火旺, two systems flagging the same misuse); *Kapha-vardhaka in excess* (guru-madhura-snigdha).

*Reasoned karma:*
- _Rasāyana_ — rejuvenative; the category into which ginseng falls most naturally (Caraka Cikitsāsthāna 1).
- _Jīvanīya_ — life-promoting; the _jīvanīya gaṇa_ register, and the candidate prabhāva above.
- _Balya, bṛṃhaṇa_ — strengthening and nourishing/anabolic.
- _Ojas-vardhana_ — ojas-promoting; the dravyaguna rendering of 大補元氣.
- _Vājīkaraṇa, vṛṣya_ — virilifying/aphrodisiac (Caraka Cikitsāsthāna 2); converging with the 補腎 register and with the one modern indication for which controlled evidence is comparatively decent (below).
- _Medhya, smṛti-prada_ — intellect- and memory-promoting (安神益智).
- _Hṛdya_ — cardiotonic.
- _Śrama-hara / klama-hara_ — fatigue- and exhaustion-relieving; the register of the modern asthenia indication.
- _Tṛṣṇā-nigrahaṇa_ — thirst-allaying (生津止渴).#footnote[Reasoned placement renders the classical Chinese 性味歸經 and indication-set onto dravyaguna axes; it is *not* a classical Ayurvedic entry — flagged. Prabhāva criterion: Caraka Saṃhitā, Sūtrasthāna 26.67–72; _rasāyana_ and _vājīkaraṇa_ categories: Caraka Cikitsāsthāna 1 and 2; the _jīvanīya gaṇa_ is a classical drug-group of Caraka. The convergence between the reasoned Pitta-vardhaka reading and the classical Chinese 實熱/陰虛火旺 contraindication is noted as a genuine cross-system agreement about *misuse*, which is often more informative than agreement about use.]

=== Viruddha (विरुद्ध — incompatibilities)

_(no classical Ayurvedic viruddha for P. ginseng — extensions of conditional rules, the classical Chinese incompatibilities, and the modern pharmacological cautions, which for this drug are substantial; tags: S core saṃhitā, N nighaṇṭu, F folk/regional, M modern/pharmacological)_

- *(extended) Conditional:* _Doṣa-viruddha_ in Pitta excess and hot-pattern states; _avasthā-viruddha_ in acute fever and acute exterior illness (the classical Chinese rule against tonifying an excess pattern); _agni-viruddha_ where _agni_ is weak and _āma_ present, a heavy tonic burdening an impaired digestion — the dravyaguna statement of the Chinese caution against tonifying through undigested stagnation; _kāla-viruddha_ in high summer for hot constitutions, though see the Climate section for the Korean counter-case.
- *(N-equivalent, Chinese canonical)* *人參反藜蘆* (antagonism with _Veratrum_, 十八反) and *人參畏五靈脂* (十九畏) — classical *Chinese* incompatibilities, tagged here because this book's tier system has no Chinese column; they are textual, not folk.
- *(F) Folk/regional:* ginseng not to be taken with *tea* or *radish/daikon* (qi-dispersing, held to undo the tonification) — widely observed in Chinese and Korean practice.
- *(M) Modern / pharmacological — genuinely substantial for this drug, unlike most entries in this book:*
  - *Anticoagulants (warfarin)* — *reduced INR* has been reported with ginseng; a controlled trial demonstrating INR reduction used *American* ginseng, and the _P. ginseng_ evidence is case-report level, so the interaction is best treated as a *genus-level caution*: patients on warfarin should not start or stop ginseng without monitoring.
  - *Antidiabetic medication* — ginseng has a modest *hypoglycaemic* effect (below); additive effect is plausible and monitoring is warranted.
  - *MAO inhibitors (phenelzine)* — case reports of headache, insomnia, tremor, and manic-type reactions; a classic herb-drug caution.
  - *Stimulants and caffeine* — additive overstimulation; consistent with the classical insomnia caution in hot constitutions.
  - *Immunosuppressants* — theoretical opposition, given the immunostimulant activity reported for ginseng polysaccharides; relevant to transplant recipients.
  - *Hormone-sensitive conditions* — weak oestrogenic activity has been reported in vitro; clinical significance is *unestablished*, and the caution is flagged as theoretical rather than demonstrated.
  - *Hypertension* — classical and modern cautions converge; the clinical data are genuinely *mixed* (both pressor and depressor effects reported), which is itself a reason for care rather than reassurance.
  - *"Ginseng abuse syndrome"* — a much-cited 1979 report (Siegel, _JAMA_) described hypertension, nervousness, insomnia, and skin eruption in high-dose chronic users. *Flagged on both sides:* the report was uncontrolled, the preparations unverified and in some cases not even Panax, and the "syndrome" has not been established as an entity — yet the described picture matches the classical caution against over-tonifying so closely that it should not be dismissed outright.
  - *Pregnancy and lactation* — insufficient human data; some animal findings on ginsenoside Rb1 raise concern; *avoid medicinal doses*. Korean dietary use in pregnancy exists culturally but is not a safety demonstration.
  - *Adulteration — a safety issue, not merely a commercial one.* Ginseng is among the most adulterated drugs in global herbal commerce; substitutions include *Codonopsis* and *Platycodon* (economically fraudulent but relatively benign) and, dangerously, *商陸 (Phytolacca,* pokeweed) root, which is *toxic*. Authenticated sourcing matters here more than for most herbs in this book.

== Traditional Arabic & Islamic Medicine (Ṭibb al-ʿArabī wa-l-Islāmī / Unani)

_Reasoned analysis, not classical._ Panax ginseng _is absent from Avicenna's_ Qānūn _and from Ibn al-Bayṭār's_ al-Jāmiʿ_. The absence is geographic and commercial rather than conceptual: medieval Arabic pharmacy received East Asian aromatics, resins, and durable goods by long-distance trade (musk, camphor, cinnamon, rhubarb, galangal), but ginseng was a *high-value, slow-growing root consumed close to its source* within the Chinese-Korean sphere, and no significant westward trade developed before the early-modern period — by which time the receiving tradition in Europe was no longer Galenic pharmacy but the beginnings of botanical science (see the Western section). The modern Arabic name is a transliteration. The reading below is reasoned extension on the humoral axis._ See `tibb-al-arabi.typ`.

*Names:* *جنسنج / جينسنغ (jinsinj / jīnsinġ)* — modern transliterations; no classical Arabic, Persian, or Urdu-Hakeemi drug-name. Modern Unani practice in South Asia has adopted ginseng as a post-classical *muqawwī* (tonic), and it appears in some contemporary Unani proprietary formulations — *a 20th-century adoption, not a classical attestation*.

*Reasoned mizāj:* *Hot and Moist, 1st–2nd degree* — the humoral rendering of 甘微苦微溫 with a nourishing, substance-building character. The placement puts ginseng among the *Hot-Moist restorative tonics*, which is a well-populated Tibb class, and *not* among the Hot-Dry stimulant aromatics; *홍삼* (red) would read at the 2nd degree and *백삼* (white) at the 1st.

*Reasoned afʿāl (actions):* *Muqawwī* in the organ-specified senses the tradition favours — *muqawwī al-qalb* (cardiac), *muqawwī al-dimāgh* (cerebral), *muqawwī al-maʿida* (gastric), *muqawwī al-aʿṣāb* (nervine); *mughadhdhī* (nourishing); *muḥarrik al-bāh* / *muqawwī al-bāh* (aphrodisiac — the action for which a Tibb physician would most readily recognize this drug, the tradition having a developed aphrodisiac-tonic class); *mufarriḥ* (exhilarant, mood-elevating); *ḥāfiẓ li-l-jasad* (body-preserving); and — the closest Tibb analogue of 大補元氣 — a *muqawwī al-rūḥ al-ḥaywānī* action on the vital spirit seated in the heart.

*Reasoned istemālāt (indications):* *ḍuʿf* (debility) and convalescence; *al-bāh* (sexual function) and *ʿuqm* (infertility) in the Unani andrological register; *khafqān* (palpitations); weakness of memory and cerebral function; cold-constitution digestive weakness.

*Reasoned mawāneʿ (contraindications):* hot and bilious (*ṣafrāwī*) temperaments, in whom a Hot restorative provokes headache, insomnia, and agitation — converging precisely with the classical Chinese 實熱 and 陰虛火旺 contraindications and with the "ginseng abuse syndrome" picture; febrile and inflammatory conditions; hypertension.

*Reasoned muṣliḥ / badal:* a Hot-Moist tonic of this class is conventionally corrected with a *cooling-moistening* adjuvant — *ʿarq-i gulāb* (rose-water), *banafsha* (violet), or a cooling *sharbat* — the same logic by which the Chinese tradition pairs ginseng with cooling 麥門冬 in 生脈散. Plausible class-level *badal* within the actual Tibb pharmacopoeia: the Unani tonic roots — *bahman surkh* and *bahman safed*, *shaqāqul* (_Pastinaca_), *tūdarī* — which occupy the restorative-aphrodisiac slot ginseng would have filled. *Explicitly reasoned, not textual:* no classical _muṣliḥ_/_badal_ table lists this drug, because the drug is not in the corpus.

*Ṭibb al-Nabawī attestation:* *none, and none possible* — the plant was unavailable in the 7th-c. Ḥijāz and absent from the Arabian and Mediterranean floras entirely. Flagged because modern Unani adoption plus the drug's tonic reputation makes a spurious pedigree easy to assert.

== Classical Formulas & Preparations

=== Chinese medicine (中醫)

- *獨參湯 (Dú Shēn Tāng)* — ginseng alone, in large dose, for qi collapse and massive blood loss; the tradition's single-herb emergency formula.
- *四君子湯 (Sì Jūnzǐ Tāng)* and its family — *六君子湯*, *香砂六君子湯*, *參苓白朮散*; the foundational Spleen-qi tonics (see `fuling.typ`).
- *補中益氣湯 (Bǔ Zhōng Yì Qì Tāng)* — Li Dongyuan's qi-raising formula for sinking middle qi and prolapse (see `astragalus.typ`).
- *生脈散 (Shēng Mài Sǎn)* — with 麥門冬 and 五味子, for qi-and-fluid depletion after heat injury; the modern injectable 生脈注射液 descends from it (see `schisandra.typ`).
- *白虎加人參湯* — high fever with fluid-and-qi damage; *四逆加人參湯* and *參附湯* — yang collapse, with aconite; the ancestor of 參附注射液 in modern Chinese critical care (_Shāng Hán Lùn_ lineage).
- *歸脾湯*, *天王補心丹*, *人參養榮湯* — spirit-calming and qi-blood-nourishing registers (see `fuling.typ`, `schisandra.typ`).
- *Preparation method is itself classical:* ginseng is traditionally *隔水燉 (gé shuǐ dùn,* double-boiled in a covered vessel set in water) to extract it gently without boiling it hard, or *含服* (a slice held in the mouth and sucked) — the latter being the standard way of taking it in debility and the method that avoids decocting the drug with cheaper herbs. *人參酒* (ginseng wine) is the alcoholic-extraction form.

=== Ayurveda

*No classical Ayurvedic formula* — non-canonical plant with no Sanskrit name. The functional slot ginseng occupies in East Asia is filled in the Indian tradition by *अश्वगन्धा (aśvagandhā)* as _rasāyana_ and _vājīkaraṇa_ drug, and secondarily by *शतावरी (śatāvarī)* and the _Cyavanaprāśa_ class — see `ashwagandha.typ`, `shatavari.typ`, `chyavanprash.typ`. Modern Indian herbal commerce sells Panax under its English name, and modern Ayurveda-adjacent products place it in the _rasāyana_ register by extension; reasoned, not classical.

=== Korean tradition (한의학 and dietetics)

_Korea has its own classical medical literature, and for this plant it is the primary tradition rather than a derivative one; this book accordingly gives it a section of its own, as `acai.typ` does for the Amazonian register._

- *동의보감 (Donguibogam, 東醫寶鑑, "Precious Mirror of Eastern Medicine")* — compiled by *허준 (Heo Jun)* and published in *1613*; the foundational Korean medical classic, inscribed on the UNESCO Memory of the World register, and the text in which the Korean handling of 인삼 is codified. *향약집성방 (Hyangyak jipseongbang, 鄉藥集成方, 1433)* — the earlier Joseon compendium of *native Korean drugs*, the work that established Korean materia medica as a tradition attending to its own flora rather than importing Chinese drug-lists wholesale.
- *경옥고 (Gyeongokgo, 瓊玉膏, "Jade Spring Paste")* — the great Korean tonic *膏 (paste/electuary)*: ginseng with *생지황* (fresh rehmannia juice), *백복령* (white poria), and *honey*, long-decocted into a dense paste and taken by the spoonful as a _rasāyana_-class longevity preparation. Recorded in the _Donguibogam_ and also in Chinese formularies, it is the preparation in which three entries of this book meet — see `rehmannia.typ`, `fuling.typ`, `honey.typ`.
- *삼계탕 (samgyetang, 蔘鷄湯,* "ginseng-chicken soup") — a young chicken stuffed with ginseng, glutinous rice, jujube, garlic, and usually *황기* (astragalus), simmered whole. *The canonical Korean dietetic preparation*, and eaten specifically on *복날 (boknal)* — the three hottest days of summer. The logic is treated in the Climate section; see also `astragalus.typ`.
- *홍삼정 (hongsamjeong)* — red-ginseng concentrate/extract, the dominant modern commercial form; *인삼차 (insam-cha)* — ginseng tea; *수삼* in *정과 (jeonggwa,* honey-candied root) and in fresh salads; *인삼주 (insam-ju)* — ginseng liquor, often with a whole root displayed in the bottle.
- *산삼 (sansam)* and the *심마니* gathering culture — see Nomenclature; wild root is consumed fresh, ceremonially, and at prices that place it outside ordinary medicine.#footnote[Korean sources: Heo Jun, _Donguibogam_ (東醫寶鑑), 1613 — the foundational Korean medical compendium (UNESCO Memory of the World, inscribed 2009); _Hyangyak jipseongbang_ (鄉藥集成方), 1433, the Joseon native-materia-medica compendium. 경옥고 (Gyeongokgo) composition (ginseng, fresh rehmannia, poria, honey) as recorded in the _Donguibogam_ and in Chinese formulary tradition — verify the exact proportions against a specific edition. Samgyetang and the 복날 custom: standard Korean food-and-medical-history literature; cf. the 황기 note in `astragalus.typ`.]

=== Western / Greco-Roman and later European medicine

*No Greco-Roman or classical European tradition* — the plant was unknown to Dioscorides, Pliny, and Galen, and the Greek-derived genus name is a Linnaean coinage, not an ancient attestation (see Nomenclature). *But the early-modern Western reception is historically consequential in its own right, and is one of the better stories in the history of global plant commerce:*

- *The Jesuit transmission.* In *1711* the Jesuit *Pierre Jartoux*, surveying in Manchuria for the Kangxi court, wrote a detailed and admiring account of ginseng — its appearance, habitat, harvest, and reputed virtues — which circulated widely in Europe. Jartoux noted that the plant's habitat resembled parts of Canada. Reading him, the Jesuit *Joseph-François Lafitau*, stationed near Montreal, searched for and in *c. 1716* identified an American congener — *_Panax quinquefolius_*, American ginseng — with Mohawk informants' help.
- *The trade inversion.* The consequence was a *transatlantic-to-transpacific trade* in which *North America exported ginseng to China*: wild American ginseng became a staple of the Canton trade, and when the *Empress of China* sailed in *1784* as the first United States vessel to trade with China, *ginseng was its principal cargo*. A North American forest root thus helped open American commerce with Asia — and the two Panax species' *opposite thermal classifications* in Chinese medicine (西洋參 cool, 人參 warm) were worked out by Chinese physicians receiving the new import, not by its exporters.
- *Taxonomy and later Western medicine.* Linnaeus named the American plant in 1753; the Asian species was formally described by *C.A. Meyer* only in *1843*. Ginseng entered 19th-c. Western eclectic and homeopathic materia medica in a minor way, and was largely dismissed by mainstream European pharmacy.
- *Modern Western pharmacology and regulation.* The 20th-c. re-entry came through two channels: the *Soviet "adaptogen" research program* (Lazarev's 1947 concept, elaborated by Brekhman from the 1950s), *in which Panax ginseng was the original and paradigm subject* — see `schisandra.typ` for the program's treatment in this book; and standardized European extracts, notably the Swiss *G115*. The *EMA/HMPC* monograph on _Panax ginseng_ radix carries a traditional-use indication for *symptoms of asthenia such as fatigue and weakness*.#footnote[Jartoux's 1711 account circulated in the Jesuit _Lettres édifiantes et curieuses_ and in English via the _Philosophical Transactions_; Lafitau's identification of _P. quinquefolius_ near Montreal followed c. 1716 — standard history-of-botany and Jesuit-science literature. The _Empress of China_ (1784), the first US ship to Canton, carried ginseng as its principal cargo: standard early-American-trade history. Linnaeus, _Species Plantarum_ (1753); C.A. Meyer (1843) for _P. ginseng_. Soviet adaptogen program: Lazarev (1947), Brekhman (1950s–60s) — see `schisandra.typ`. EMA/HMPC monograph on _Panax ginseng_ C.A. Meyer, radix — verify the current revision and the exact indication wording.]

=== Tibb (Arabic-Islamic)

*No classical preparation* — see the Tibb section above. Modern Unani proprietary tonics incorporating ginseng are a 20th-c. adoption.

== Climate, Constitution & Regional Diet

_P. ginseng_ is a *cool-temperate, shade-demanding forest-understory perennial* with exacting requirements: cold winters, humus-rich well-drained soil, deep shade, and *four to six years* to reach medicinal maturity. It cannot be hurried, and it *exhausts its ground* — a cultivated plot typically cannot grow ginseng again for a decade or more. These facts, rather than any market preference, explain why the drug has always been expensive. See `climates.typ`.

=== Cool-temperate continental East Asia (the native and canonical zone)

Köppen Dwa/Dwb — cold dry winters, warm humid summers: the Korean peninsula, Northeast China (Jilin, the *長白山 / 백두산* range), and the Russian Primorye. Constitutionally the long cold winter carries *寒* with Kidney-yang loading, and Vāta-Kapha in dravyaguna terms; the humid summer brings 暑 and 濕. *Traditional preparation and cares.* This is the zone of the *processing* system: *홍삼* (steaming) and *흑삼* (repeated steaming) exist because a cold-winter culture wanted a *warmer, more concentrated, storable* form of a slightly-warm root — the saṃskāra is a climatic adaptation as much as a pharmacological one. The constitutive cares are *small dose, long course, and gentle extraction* (隔水燉, double-boiling) rather than hard decoction; and *reservation* — ginseng is a drug for the depleted, not a daily beverage, and the tradition's own caution against tonifying repletion is the operative rule.

=== The Korean summer paradox — 이열치열 (以熱治熱, "treat heat with heat")

The most instructive climatic fact about this drug is that Koreans eat *삼계탕* — a hot soup of chicken, ginseng, and astragalus — on *복날*, the three *hottest* days of the year. This looks like a category error and is not. The classical rationale is *暑傷氣 (shǔ shāng qì,* "summer-heat damages qi"): profuse sweating in humid heat depletes qi and fluids, the exterior is hot while the interior becomes *cold and depleted*, and the correct intervention is therefore *warming tonification*, not cooling. The principle is Korean *이열치열* / Chinese *以熱治熱*, and it is not folk improvisation — it is the same reasoning that produces *生脈散* and the 清暑益氣 (clear-summerheat-and-augment-qi) formula class for exactly this presentation. *Cares:* the preparation is constitutive — the ginseng comes *with* chicken (nourishing), jujube (moderating), and glutinous rice (supporting the Spleen), as a *meal* rather than a drug dose, which is what makes a warming tonic tolerable in high summer. Taken as a concentrated extract in the same weather by a hot constitution, the same drug would be straightforwardly inappropriate. This is one of the cleanest demonstrations in this book that *climate, constitution, and preparation form a single argument*.

=== Hot-humid subtropical and tropical (the export markets)

Köppen Cfa/Am — southern China, Hong Kong, Taiwan, Southeast Asia; external *濕熱*, Pitta-Kapha with Spleen loading. Here the classical logic is visible *in the market itself*: southern-Chinese and Southeast-Asian consumers characteristically prefer *西洋參 (American ginseng — cool, yin-and-fluid-tonifying)* over warm Korean *홍삼*, and prepare it as a cooling double-boiled soup or a tea. *This is the climate framework operating as consumer behaviour*: the same genus, selected by thermal property to match the climate and constitution, with the cool species chosen where damp-heat prevails. It is rare to find the doctrine of `climates.typ` expressed so directly in trade statistics.

=== Temperate North America (the inverted-trade zone)

Köppen Dfa/Dfb — the deciduous forests of Appalachia, Wisconsin, Ontario and Quebec: the home of *_P. quinquefolius_*, and the site of the historical inversion described above, in which a Western hemisphere with no medical tradition for the plant became a major *supplier* to one that had. Wild-harvest pressure has made American ginseng a conservation concern and a regulated commodity.

=== Climates where ginseng is not traditional

South Asia, the Middle East, Africa, Europe, and Latin America have no traditional use: the Ayurvedic, Tibb, and Greco-Roman absences treated above are *geographic*, compounded for this plant by a growth requirement (cold-winter forest understory, several years to maturity) that made casual transplantation impossible. The *indications* travel freely — fatigue and debility are universal; the plant does not.

=== Modern transposition (_deśa-viruddha_ / _kāla-viruddha_, Caraka Sūtra 26)

Four transposition problems, and this drug has more of them than most. First, *dose and duration*: the classical register is *small doses for the genuinely depleted, in courses*, whereas the global supplement register is *daily, indefinite, by the healthy* — precisely the over-tonification the tradition warns against, and arguably what the "ginseng abuse syndrome" reports were describing. Second, *constitution*: the single most-ignored classical rule is the contraindication in heat and repletion patterns; a hot, robust, hypertensive consumer taking red-ginseng extract year-round is a textbook _doṣa-viruddha_ case. Third, *the "adaptogen" framing itself* — a 20th-c. Soviet pharmacological concept (see `schisandra.typ`), not a classical category — recasts a pattern-matched tonic as a *universal* stress-buffer appropriate to everyone, which erases the very constitutional discrimination that governed its classical use. Fourth, *season*: the Korean tradition's own summer use is *hedged by preparation* (a meal, not an extract) in a way the global market does not reproduce; _kāla-viruddha_ applies to the extract and not to the soup. See `climates.typ`.

== Modern Nutrition & Pharmacology

Ginseng is a medicinal root taken in gram doses, not a food; no per-100 g macronutrient profile is meaningful (the fresh root eaten in *삼계탕* or candied is a minor contribution). Its pharmacology is dominated by one well-characterized class of constituents, and by a processing chemistry that vindicates a classical distinction.

*Key constituents:*
- *Ginsenosides (dammarane-type triterpene saponins)* — the defining class, with upwards of a hundred identified. Two principal groups: *protopanaxadiol (PPD)* type — *Rb1, Rb2, Rc, Rd* — and *protopanaxatriol (PPT)* type — *Rg1, Re, Rf*; plus the oleanane-type *Ro*. Ginsenoside profile differs by species, which is why the drugs differ: *Rf* is characteristically present in _P. ginseng_ and essentially absent in _P. quinquefolius_, a marker used for authentication.
- *The red-ginseng transformation — the modern vindication of 홍삼.* Steaming *chemically transforms* the saponins: polar and malonyl ginsenosides are partly deglycosylated and dehydrated to *less-polar species*, notably *Rg3, Rg5, Rk1*, which are *absent or minimal in white ginseng and generated by the processing*. Since several of these are more readily absorbed and more active in standard models, *the classical claim that red ginseng is a stronger and warmer drug than white has a specific chemical correlate.* This is the same kind of saṃskāra-vindication as gingerol→shogaol in `ginger.typ` and the rind-concentrated triterpenes in `fuling.typ`, and it is among the best-documented instances in the whole materia medica.
- *Compound K* — the principal *intestinal microbial metabolite* of PPD-type ginsenosides and, on current understanding, a major bioavailable active principle. *The implication is unusual and worth stating:* because conversion depends on gut flora, *individuals differ in their capacity to activate the drug*, which supplies a genuinely modern mechanism for the old clinical observation that ginseng suits some constitutions and not others. Flagged as a mechanism with suggestive rather than established clinical application.
- *Polysaccharides (panaxans)* — implicated in the immunomodulatory and glycaemic effects; *polyacetylenes* (panaxynol/falcarinol class); *peptides, phenolics, and trace minerals*.#footnote[Phytochemistry: the PPD/PPT ginsenoside classification and the species-marker role of Rf; the steaming-induced conversion of polar/malonyl ginsenosides to Rg3, Rg5 and Rk1 in red ginseng; compound K as the gut-microbiota metabolite of PPD ginsenosides and its interindividual variability — standard _Panax ginseng_ phytochemistry and pharmacokinetics reviews; verify against current literature. The correspondence between the red/white classical distinction and the ginsenoside transformation is a genuine convergence, noted as such and not as evidence that the classical distinction was chemically motivated.]

*Pharmacology of note — with evidence tiers kept explicit:*
- *Asthenia, fatigue, quality of life* — the indication with regulatory standing (EMA/HMPC traditional use); trial evidence is *modest and heterogeneous*, with better signals in fatigued and clinical populations than in healthy volunteers.
- *Glycaemic control* — meta-analyses of ginseng supplementation report *modest reductions* in fasting glucose; effects are small, preparation-dependent, and not a substitute for established therapy. One of the better-supported effects nonetheless.
- *Erectile function* — *Korean red ginseng* has the comparatively strongest controlled evidence of any indication here, with several randomized trials and meta-analyses reporting benefit in erectile dysfunction; effect sizes are moderate and trial quality variable. This converges with the classical 補腎 and reasoned _vājīkaraṇa_ registers.
- *Cognition and mood* — small trials report modest short-term effects on working memory and subjective calm/alertness; evidence is *preliminary* and the literature is noisy.
- *Immune function and vaccine response* — polysaccharide-mediated immunomodulation is well demonstrated preclinically; human outcomes (respiratory-infection incidence, vaccine response) show modest and inconsistent benefit.
- *Blood pressure* — *genuinely mixed*: both small pressor and small depressor effects are reported, and the honest summary is that the net clinical effect is unclear, which supports caution rather than confidence in hypertensive patients.
- *Cancer-related fatigue* — some randomized support exists in oncology supportive care, though the most-cited trials used *American* ginseng; do not transfer the result across species without checking.
- *"Adaptogen"* — flagged as a *20th-c. Soviet pharmacological concept* (see `schisandra.typ`), not a classical category and not a regulatory one; useful as a research heuristic, misleading as a claim of universal applicability.#footnote[Clinical evidence: EMA/HMPC monograph and assessment report on _Panax ginseng_ radix (asthenia/fatigue, traditional use); meta-analyses of ginseng on fasting glucose and on erectile dysfunction (the latter specifically Korean red ginseng); trials in cognition, immune function, and blood pressure; oncology supportive-care trials (note that the most-cited fatigue trials used _P. quinquefolius_). All require current verification; evidence tiers are stated as modest-to-preliminary deliberately, and the mixed blood-pressure findings are presented as mixed rather than resolved.]

*Safe daily dosage / upper limit:* the limiting consideration for ginseng is *constitutional suitability and duration*, not organ toxicity — there is no sharply defined toxic constituent as with thujone in sage or glycyrrhizin in licorice.
- *Chinese decoction dose:* *3–9 g/day* of the dried root (consistent with the 3–10 g figure given in `astragalus.typ`), with *15–30 g or more* in *獨參湯* for acute collapse — a hospital-register dose, not a self-care one.
- *Korean red ginseng:* commonly *2–6 g/day* of root, or the equivalent as *홍삼정* concentrate.
- *Standardized extract:* the *G115*-type extract is conventionally dosed at *200 mg/day* (standardized to ~4% ginsenosides).
- *Course rather than continuous use:* the traditional practice of *cycling* (courses with breaks, and seasonal use) aligns with both the classical over-tonification caution and the "abuse syndrome" picture; continuous indefinite high-dose use has no traditional warrant.
- *Avoid / use only under supervision:* acute febrile and exterior illness; *excess-heat and yin-vacuity-with-fire patterns*; *uncontrolled hypertension*; *pregnancy and lactation* (medicinal doses); concurrent *warfarin*, *MAOIs*, *antidiabetic medication*, or *immunosuppressants* (see Viruddha).
- *Authentication matters unusually much:* prefer pharmacopoeial or reputably certified material, given documented adulteration including *toxic Phytolacca* substitution.
- *Reference thresholds, not personalized medical advice;* ginseng is a potent drug with real interactions, and the classical tradition's own insistence that it be matched to a pattern is good advice rather than quaint.#footnote[Dosing: _Chinese Pharmacopoeia_ monograph for 人參 and Bensky, Clavey & Stöger, _Materia Medica_, 3rd ed. (3–9 g, with the high-dose 獨參湯 exception); Korean Pharmacopoeia for _Ginseng Radix Rubra_; EMA/HMPC monograph posology; G115 extract dosing from the standardized-extract literature. Adulteration including _Phytolacca_ substitution: pharmacognostic authentication literature. Reference thresholds requiring current verification, not medical advice.]

== Sources

- _Shennong Bencao Jing_ (神農本草經), Han period — 人參, 上品 classification.
- Li Shizhen, _Bencao Gangmu_ (本草綱目), 1578 — 人參 entry, drug-forms, the man-shaped-root grading.
- Zhang Zhongjing, _Shāng Hán Lùn_ (傷寒論) — 白虎加人參湯, 四逆加人參湯; _Tài Píng Huì Mín Hé Jì Jú Fāng_ (1108) — 四君子湯.
- Li Dongyuan, _Pi Wei Lun_ (脾胃論, 12th c.) — 補中益氣湯; Zhang Yuansu, _Yi Xue Qi Yuan_ (醫學啟源, 12th c.) — 生脈散; Yan Yonghe, _濟生方_ (13th c.) — 歸脾湯; Ge Qiansun, _Shí Yào Shén Shū_ (十藥神書, 14th c.) — 獨參湯 (attribution to be verified).
- Heo Jun, _Donguibogam_ (東醫寶鑑), 1613 — the foundational Korean medical compendium; _Hyangyak jipseongbang_ (鄉藥集成方), 1433 — Joseon native materia medica; both for the Korean handling of 인삼 and for 경옥고.
- _Chinese Pharmacopoeia_ and _Korean Pharmacopoeia_ (current editions) — 人參 / _Ginseng Radix_ and _Ginseng Radix Rubra_ monographs.
- Bensky, Clavey & Stöger, _Chinese Herbal Medicine: Materia Medica_, 3rd ed.; Bensky & Barolet, _Formulas & Strategies_, 2nd ed.
- Jartoux's 1711 ginseng account (_Lettres édifiantes et curieuses_; English via the _Philosophical Transactions_); Lafitau's c. 1716 identification of _P. quinquefolius_; early-American China-trade history for the _Empress of China_ (1784).
- Linnaeus, _Species Plantarum_ (1753); C.A. Meyer (1843) for _P. ginseng_; Liddell & Scott (πάναξ, πανάκεια); _Oxford English Dictionary_ (s.v. "ginseng").
- Lazarev (1947) and Brekhman (1950s–60s) on the adaptogen concept — see `schisandra.typ`.
- EMA/HMPC monograph and assessment report on _Panax ginseng_ radix; current meta-analyses on glycaemic control, erectile dysfunction (Korean red ginseng), fatigue, cognition, and immune endpoints; current phytochemistry and pharmacokinetic reviews on ginsenosides, red-ginseng transformation, and compound K; pharmacognostic literature on adulteration — all to be verified against current editions.
- Siegel, _JAMA_ (1979), on "ginseng abuse syndrome" — cited with its methodological limitations stated.
- Foundational and sibling frameworks: `tibb-al-arabi.typ`, `climates.typ`, `zz-glossary.typ`; the companion qi-tonic and formula entries `astragalus.typ`, `fuling.typ`, `schisandra.typ`, `rehmannia.typ`, `dang-gui.typ`, `chinese-licorice.typ`, `honey.typ`; the functional-analogue and misnomer entries `ashwagandha.typ`, `shatavari.typ`, `chyavanprash.typ`; the 參-suffix disambiguation in `sage.typ`; the saṃskāra parallels in `ginger.typ` and `rehmannia.typ`.
