= Chamomile (Camomila)

_Scope: this entry treats the two classical chamomiles — *Matricaria chamomilla* L. (= *M. recutita* L.), *German chamomile*, the principal drug of modern phytotherapy and of Tibb *bābūnaj*, whose drug is the dried flower-head (*Matricariae flos*); and *Chamaemelum nobile* (L.) All. (= *Anthemis nobilis* L.), *Roman chamomile*, a distinct genus with a different essential-oil chemistry, used more for oil and topical/perfumery purposes. Two disambiguations are load-bearing: (1) chamomile is *not* Chinese chrysanthemum — 菊花 (júhuā, *Chrysanthemum × morifolium*) is an unrelated Asteraceae with its own deep Bencao tradition, treated in chrysanthemum.typ, and the modern Chinese name for chamomile, 洋甘菊 ("foreign sweet-chrysanthemum"), has caused a real and traceable misassimilation of the two, flagged below; (2) German and Roman chamomile are different plants with different chemistry and should not be read off each other. Status: deeply classical in Greco-Roman medicine (Dioscorides' χαμαίμηλον, Galen's chamomile oil) and well developed in Tibb (bābūnaj); not classical in Chinese medicine or in Ayurveda — those sections are reasoned extension, flagged as such. Modern status is exceptional: chamomile carries one of the best-developed regulatory-phytotherapy dossiers of any plant in this book (German Commission E; EMA/HMPC), and is among the most universally used household herbs in Brazil (chá de camomila)._

== Nomenclature & Etymology

*Latin / botanical:* *_Matricaria chamomilla_ L.* (= _M. recutita_ L.; both names remain in wide pharmacognostic use, the nomenclatural priority having been contested through the 20th c.), family Asteraceae (Compositae); the drug is the *dried flower-head*, officinal as *_Matricariae flos_*. *_Chamaemelum nobile_ (L.) All.* (= _Anthemis nobilis_ L.) — *Roman chamomile*, a perennial of a separate genus, *lower in apigenin and chamazulene and higher in angelate esters*, used principally for its essential oil and in topical/perfumery registers rather than for the internal digestive use of German chamomile.#footnote[Species delimitation and the _M. chamomilla_/_M. recutita_ nomenclatural history: standard pharmacognosy references (Evans, _Trease and Evans' Pharmacognosy_); the officinal drug _Matricariae flos_ and the German/Roman chamomile distinction: EMA/HMPC monograph on _Matricaria recutita_ L., flos, and the corresponding _Chamaemelum nobile_ material. The two are routinely conflated in popular herbal literature — flagged.]

*Etymology — "chamomile":* from Greek *χαμαίμηλον (chamaímēlon)* — *χαμαί (chamaí,* "on the ground, low, dwarf") + *μῆλον (mêlon,* "apple") — literally *"ground-apple,"* for the apple-like scent released when the fresh flowers and foliage are crushed or trodden. This is the *same μῆλον root* treated in this book's apple entry (the generic Greek-Latin "tree-fruit/round-fruit" word that generated quince, peach, apricot, citron, and pomegranate as compound _mêlon_-names); chamomile's name is thus "the low apple," a purely olfactory metaphor with no botanical relation to _Malus_. The compound is used by both *Dioscorides* and *Galen*. The Latin forms *_chamomilla_* and *_camomilla_* descend directly from it.#footnote[Etymology: Liddell & Scott, _A Greek–English Lexicon_ (s.v. χαμαί, μῆλον, χαμαίμηλον); Lewis & Short, _A Latin Dictionary_ (s.v. _chamaemelon_, _chamomilla_). The apple-scent motivation is standard and uncontested. Cross-reference `apple.typ` for the μῆλον/_mālum_ root and its compound-fruit family.]

*Genus name "Matricaria":* from Latin *_mātrīx_ / _māter_* ("womb, mother") — the genus name directly encodes the plant's traditional standing as a *uterine and gynaecological remedy* (emmenagogue, soother of menstrual and uterine complaint), one of the more transparent cases in Western pharmacobotany of a botanical name preserving the classical indication. The etymology and a live modern safety caution converge rather than merely coincide: the same uterine-stimulant tradition that produced the name underwrites the modern pregnancy caution on concentrated preparations (below) — *the name and the caution point the same direction*.#footnote[_Matricaria_ < _mātrīx_/_māter_: Lewis & Short, _A Latin Dictionary_ (s.v. _matrix_); the naming-after-indication pattern is discussed in standard historical herbals (Grieve, _A Modern Herbal_, 1931, s.v. chamomile). The convergence with the modern pregnancy caution is noted as an observation, not as evidence for either claim.]

*English:* *chamomile* (also *camomile*), via Old French _camomille_ from Latin _chamomilla_; the *"German"* and *"Roman"* qualifiers are early-modern English trade terms distinguishing the two genera, and are geographically misleading — "Roman" chamomile is not especially Roman, the epithet deriving from a 16th-c. botanist's description of plants found near Rome.#footnote[_Oxford English Dictionary_ (s.v. "camomile | chamomile, n."); the "Roman" epithet's origin in a 16th-c. description rather than any Roman-antiquity association is standard in horticultural-history literature — flagged because the name invites a false classical inference.]

*Greek:* *χαμαίμηλον (chamaímēlon)*; also *ἀνθεμίς (anthemís)* — and here lies a genuine *classical identification problem* rather than a tidy correspondence. Dioscorides (_De Materia Medica_ III) describes several _anthemis_/_chamaímēlon_ kinds distinguished by flower colour, and the mapping of his kinds onto the modern species (_Matricaria chamomilla_, _Chamaemelum nobile_, _Anthemis_ spp. proper) is *not securely resolved*; the ancient terms covered a cluster of similar Asteraceae. Modern Greek *χαμομήλι (chamomíli)* continues the ancient word.#footnote[Dioscorides, _De Materia Medica_ III (Beck translation, Olms-Weidmann, 2005) — the _anthemis_/_chamaímēlon_ kinds and their uncertain mapping onto modern species is discussed in the standard commentary literature on Dioscorides; the identification should be treated as approximate. This is the same class of problem as the _silphium_ puzzle in `asafoetida.typ`, though far less severe.]

*Latin pharmacy:* *_Flores Chamomillae_*, *_Anthemidis flores_* (Roman chamomile), *_Infusum Anthemidis_*, *_Oleum Chamomillae_* (the infused/macerated oil, distinct from the steam-distilled essential oil) — the officinal names of European pharmacy.

*German:* *Kamille*, *Kamillentee*, *Kamillenblüten* — Germany is the centre of the modern clinical-and-regulatory chamomile tradition (Commission E; the long-marketed _Kamillosan_ preparations), and German chamomile's very English name records that centrality.

*Arabic / Persian / Urdu (Tibb):* *بَابُونَج (bābūnaj)* — the canonical Arabic pharmacological name, and in this book's glossary the Tibb framework-term for digestive-and-calming Asteraceae bitters generally (extended, in `lucera.typ`, to the unrelated South American _Pluchea sagittalis_). Also *بَابُونَة (bābūna)*. Persian: *بابونه (bābūne)*. Urdu/Hakeemi: *بابونہ (bābūnah)*, *گل بابونہ (gul-e bābūnah)*. The ultimate derivation of _bābūnaj_ is *not securely established* — a Persian-mediated route is commonly proposed, and some lexicographers suggest an ultimate relation to the Greek register, but the word should not be presented as a straightforward borrowing from _chamaímēlon_.#footnote[بابونج in Ibn Sīnā, _al-Qānūn_ II (_al-adwiya al-mufrada_), and Ibn al-Bayṭār, _al-Jāmiʿ_; the name's uncertain ultimate etymology: Lane, _An Arabic-English Lexicon_ (s.v. بابونج) — flagged as unresolved rather than assigned a confident Greek derivation.]

*Portuguese (Brazilian):* *camomila* — among the most universally known household herbs in Brazil and Portugal; *chá de camomila* is a near-default domestic remedy for infant colic, agitation, and sleep, and the commercial dried flower is sold in every Brazilian supermarket and pharmacy. (*Maçanilha* survives as an older/regional Portuguese form, parallel to the Spanish.)

*Spanish:* *manzanilla* — literally *"little apple,"* an *independent calque of the same apple-scent motivation* that produced the Greek _chamaímēlon_: two unrelated traditions arriving at "little apple" for the same plant for the same reason. _Manzanilla_ already appears in this book's glossary among the Argentine-Uruguayan *yerbas digestivas*, alongside quitoco/lucera and boldo — see `lucera.typ`.

*Sanskrit:* *no classical name.* _Matricaria_ is a Mediterranean/West-Asian Asteraceae, post-classical in India, with no entry in Caraka, Suśruta, or the nighaṇṭus. The modern Indian name *बबूना (babūnā)* / *बाबूना* is a *Unani borrowing of the Arabic bābūnaj*, not a Sanskrit lemma — its presence in Indian herbal commerce is an artefact of the Greco-Arabic transmission into South Asia, not of the Ayurvedic canon. Treated as reasoned-only below.#footnote[The Hindi/Urdu _babūnā_ is a loan from Arabic بابونج via the Unani tradition, not a Sanskrit or classical Ayurvedic name; Monier-Williams has no corresponding classical lemma. The distinction matters: a plant present in modern Indian herbal markets under an Arabic-derived name is a Unani import, not an Ayurvedic drug — flagged.]

*Chinese:* *洋甘菊 (yáng gānjú, "foreign sweet-chrysanthemum")* — the modern Chinese name, with the *洋* ("foreign, overseas") prefix marking the Western import, exactly the convention seen in *洋艾* ("foreign mugwort") for European wormwood against the native classical Artemisia drugs (see `wormwood.typ`, and the glossary's 胡-/洋-prefix note). *A flagged misassimilation:* because the coined name contains 菊 (jú, chrysanthemum), modern Chinese popular and commercial herbal literature frequently assimilates 洋甘菊 to the cooling 菊花 register and describes it as 微寒 (slightly cold) — whereas the *classical Greco-Arabic and Galenic reading of chamomile is Hot and Dry*. The "cooling chamomile" now common in both Chinese popular sources and Western wellness writing is thus a *name-and-register artefact*, not a classical attribution, and the cross-system divergence is discussed in the CCM and Tibb sections rather than smoothed over.

== Classical Chinese Medicine (中醫) View

_Chamomile has no classical Chinese entry_ — it is a Mediterranean Asteraceae outside the _Bencao_ tradition, named in Chinese only in the modern period as 洋甘菊. *A hard disambiguation first:* the classical Chinese flower-drug that English-language sources sometimes allow to blur into "chamomile" is *菊花 (júhuā)*, the flower of _Chrysanthemum × morifolium_ — pungent-sweet-bitter, slightly cold, entering Lung and Liver, a *疏散風熱* and *清肝明目* drug with _Shennong Bencao Jing_ superior-grade standing (see `chrysanthemum.typ`). *That is a different genus, a different chemistry, and a different action, and the two must not be merged.* The reading below is *reasoned extension* for _M. chamomilla_, by analogy to other aromatic carminative-and-spirit-calming flower and aerial-part drugs — flagged, not canonical.

*Property (by reasoned extension):* Neutral to slightly warm (平–微溫), aromatic. *This is a deliberate divergence from the modern Chinese popular placement of 洋甘菊 as 微寒 (slightly cold)*, which this entry treats as an artefact of the 菊-containing coined name (above) rather than a reasoned pharmacological reading; the warm-aromatic placement follows the Galenic *warm-dry* and Tibb *Hot* attributions and the drug's carminative-antispasmodic behaviour, and the divergence is flagged rather than reconciled.

*Flavor:* Pungent (辛), bitter (苦), slightly sweet (甘), aromatic (香).

*Channels (by extension):* Liver (肝), Spleen (脾), Stomach (胃), Heart (心).

*Actions (by extension):*
- *理氣止痛 (lǐ qì zhǐ tòng)* — regulates qi and stops pain: the antispasmodic/colic register, the best-attested of chamomile's modern pharmacological actions and the core of its Western and Tibb use.
- *和中 / 健脾和胃 (hé zhōng / jiàn pí hé wèi)* — harmonizes the middle, the digestive-tea register for dyspepsia and bloating.
- *疏肝解鬱 (shū gān jiě yù)* — soothes the Liver and resolves constraint: the reasoned reading of the anxiolytic/tension indication, the category to which a Chinese clinician would most naturally assign a mildly bitter-aromatic calming flower.
- *安神 (ān shén)* — calms the spirit (the sleep and agitation register; modern pharmacology supplies an apigenin/GABA-A mechanism, below).
- *清熱消腫 (qīng rè xiāo zhǒng)* — clears heat and reduces swelling: the topical anti-inflammatory register (compresses, washes, mouthwash) — the one action for which a *cooling* reading is defensible, and plausibly part of why the "cooling chamomile" perception arose.

*Cautions (by extension):* pregnancy (the emmenagogue tradition, below); Asteraceae-family sensitization (a modern rather than classical category, but the operative practical caution); no classical 配伍禁忌 applies, there being no classical entry.#footnote[Reasoned placement only; _M. chamomilla_ has no _Bencao_ entry and no classical 性味歸經 attribution. The reasoned axes follow the Galenic/Tibb warm-aromatic reading and the modern antispasmodic-anxiolytic pharmacology; the explicit divergence from modern Chinese popular sources' 微寒 placement of 洋甘菊 is flagged as a naming artefact. For the genuinely classical Chinese flower-drug 菊花, see `chrysanthemum.typ` and Bensky, Clavey & Stöger, _Materia Medica_, 3rd ed.]

== Ayurvedic Dravyaguna (द्रव्यगुण)

_Reasoned analysis, not classical._ Matricaria chamomilla _is a post-classical introduction to India with no entry in Caraka, Suśruta, or the nighaṇṭus; its Indian presence is a Unani transmission under the Arabic-derived name_ babūnā _(see Nomenclature). The reading below applies dravyaguna principles by extension, in the register of the other reasoned-only European-herb entries (`sage.typ`, `oregano.typ`)._

*Reasoned rasa:* Tikta (तिक्त, bitter — the dominant note), Kaṭu (कटु, pungent), with a faint Madhura (मधुर, sweet) edge in the honeyed floral aroma.

*Reasoned guṇa:* Laghu (लघु, light), Rūkṣa (रूक्ष, dry), Sūkṣma (सूक्ष्म, subtle — the penetrating aromatic quality that reaches the _srotas_), Sugandhi (सुगन्धि, fragrant).

*Reasoned vīrya:* Uṣṇa (उष्ण, heating) — converging with the Tibb *Hot* and the Galenic *warm-dry* readings, and *diverging from the popular modern "cooling chamomile" perception*; the divergence is flagged rather than averaged out. A minority reasoned case for mild śīta could be built from the topical anti-inflammatory use alone, but the carminative-antispasmodic core behaviour and the whole classical Western-Arabic tradition favour uṣṇa.

*Reasoned vipāka:* Kaṭu (कटु, pungent).

*Prabhāva:* *None classically* — there being no classical entry, no prabhāva is assigned. If one were singled out, the candidate is the *combination of mild anxiolysis with genuine smooth-muscle antispasmodic action at ordinary food-tea dose* — a pairing not obviously predictable from a light, dry, bitter-pungent aromatic, and now given a mechanistic account (apigenin at the GABA-A benzodiazepine site, plus bisabolol/spiroether antispasmodic activity, below). Flagged as *modern interpretive*, not classical.

*Reasoned doṣa effect:* Vāta-śāmaka (the uṣṇa-sūkṣma profile, with the _anulomana_ action on colicky, upward-displaced Vāta) and Kapha-śāmaka (laghu-rūkṣa-tikta); Pitta-vardhaka in excess, though mildly so — chamomile is a gentle drug and the Pitta caution is slight compared with sage or wormwood.

*Reasoned karma:*
- _Dīpana, pācana_ — digestive-kindling and āma-digesting (the after-meal infusion register).
- _Vāta-anulomana_ — restores Vāta's downward flow; relieves bloating and colic.
- _Śūla-praśamana_ — relieves colicky pain (the signature reasoned action; the infant-colic and menstrual-cramp register in which chamomile is used worldwide).
- _Nidrā-janana_ — sleep-promoting.
- _Manaḥ-praśamana / manas-prasādana_ — mind-calming and mood-settling (cf. the jasmine prabhāva register in `jasmine-flowers.typ`).
- _Ārtava-janana_ — emmenagogue; the basis of the pregnancy caution and the correlate of the Latin _Matricaria_ naming and the Tibb _mudirr li-l-ḥayḍ_.
- _Vraṇa-ropaṇa, tvacya_ — wound-healing and skin-benefiting (the topical/compress register).
- _Dāha-praśamana_ (topical only) — relieves burning and inflammation of the skin and mucosa.#footnote[Reasoned placement anchors on the pharmacologically real antispasmodic, anxiolytic, emmenagogue, and topical anti-inflammatory actions; it is *not* a classical Ayurvedic entry — flagged. The uṣṇa vīrya assignment deliberately follows the Galenic/Tibb tradition against the popular modern "cooling" reading; the divergence is a genuine cross-system disagreement, noted per this book's standard. _Śūla-praśamana_ and _ārtava-janana_ are added to the glossary with this entry.]

=== Viruddha (विरुद्ध — incompatibilities)

_(no classical viruddha for M. chamomilla — extensions of conditional rules plus modern pharmacological cautions; tags: S core saṃhitā, N nighaṇṭu, F folk/regional, M modern/pharmacological)_

- *(extended) Conditional:* Pitta excess and hot-pattern conditions in quantity (the uṣṇa note — mild); _agni_-independent, being a gentle drug.
- *(F) Folk/regional:* the Brazilian and Iberian domestic register pairs camomila with *erva-cidreira* and *maracujá* in calming blends and treats it as suitable for infants — a living folk practice, noted as (F)-tier, with the modern pediatric qualification below.
- *(M) Modern / pharmacological:*
  - *Asteraceae (Compositae) cross-allergy* — the most substantial modern caution: contact dermatitis and, rarely, severe reactions including anaphylaxis in individuals sensitized to ragweed, mugwort, or other Compositae. Reported disproportionately with *Roman chamomile / Anthemis* material and with *eye-wash* use (conjunctival exposure), rather than with ordinary German-chamomile tea — a distinction worth preserving rather than collapsing into a blanket warning.
  - *Pregnancy* — concentrated extracts and the essential oil are *to be avoided* (emmenagogue tradition; _ārtava-janana_ / _mudirr li-l-ḥayḍ_); ordinary culinary-tea quantities are generally regarded as lower-risk, but current guidance should be checked. The convergence of the _Matricaria_ etymology, the classical emmenagogue attribution, and the modern caution is noted in Nomenclature.
  - *Anticoagulant therapy* — coumarin-class constituents (herniarin, umbelliferone) support a *theoretical* interaction with warfarin and other anticoagulants; clinical significance at tea doses is considered low, and the caution is flagged as theoretical rather than demonstrated.
  - *Sedative potentiation* — mild additive effect with benzodiazepines, Z-drugs, alcohol, and other sedating agents, consistent with the apigenin/GABA-A mechanism.
  - *Infants* — chamomile tea is a near-universal domestic remedy for colic across European and Latin-American traditions; national pediatric guidance on herbal teas for infants nevertheless varies, and *if the infusion is sweetened with honey the infant-botulism contraindication applies to the honey, not the chamomile* (see `honey.typ`).

== Traditional Arabic & Islamic Medicine (Ṭibb al-ʿArabī wa-l-Islāmī / Unani)

Chamomile is *classical in Tibb* under *بَابُونَج (bābūnaj)* — a mild warming-resolvent *deobstruent, antispasmodic, and calmative*, inherited from the Greek _chamaímēlon_ and elaborated across the Arabic, Persian, and South-Asian Unani tradition; in this book it also serves as the *framework drug* for digestive-and-calming Asteraceae generally (see `lucera.typ`). See `tibb-al-arabi.typ` for the humoral frame.

*Arabic:* *بَابُونَج (bābūnaj)*, *بَابُونَة (bābūna)*. Persian: *بابونه (bābūne)*. Urdu/Hakeemi: *بابونہ (bābūnah)*, *گل بابونہ (gul-e bābūnah)*.

*Mizāj:* *Hot and Dry in the 1st degree* in the standard Unani pharmacopoeial placement — a *mild* warming-drying simple, notably gentler than sage (Hot-Dry 2nd) or wormwood (Hot 1st, Dry 2nd–3rd); sources vary, with some giving Hot-Dry in the 2nd degree, and the precise _darajāt_ should be verified against a specific _Qānūn_ edition rather than taken from secondary compilations. *This Hot placement is the principal cross-system divergence of the entry*, standing against the modern popular "cooling chamomile" reading (see Nomenclature and the Ayurveda section).#footnote[Mizāj and actions of بابونج: Ibn Sīnā, _al-Qānūn_ II; Ibn al-Bayṭār, _al-Jāmiʿ_; AYUSH/CCRUM, _National Formulary of Unani Medicine_, and _Khazāyin al-Adwiya_ for the later Unani register. The Hot-Dry 1st-degree placement is the common attribution, with 2nd-degree variants in some sources — flagged for verification against a specific edition, per this book's sourcing standard.]

*Afʿāl (actions):*
- *Mufattiḥ* — deobstruent; opens obstructions (_suddad_) of liver, spleen, and vessels: a leading classical attribution.
- *Muḥallil* — resolvent; disperses swellings and inflammatory accumulations (the poultice and bath register).
- *Musakkin li-l-alam* — pain-calming/analgesic, specifically of colicky and cramping pain.
- *Kāsir li-l-riyāḥ*, *hāḍim*, *muqawwī al-maʿida* — carminative, digestive, stomach-tonic.
- *Mulayyin* — mildly laxative/relaxing.
- *Munawwim (khafīf)* — mildly hypnotic; *mufarriḥ* in a mild degree (mood-settling).
- *Mudirr li-l-ḥayḍ* — emmenagogue (hence the pregnancy caution); *mudirr li-l-bawl* in a minor degree.
- *Mujaffif*, *jālī* — drying and cleansing (wounds, mucosa).

*Istemālāt (indications):* colic and griping abdominal pain; flatulent dyspepsia and weak digestion; menstrual retention and cramping; *amrāḍ al-mafāṣil* (joint pains) by fomentation and bath; headache of cold/windy type; inflammations and swellings topically; sore and inflamed mucosa (mouth, throat, eye-wash in the classical register — the eye use carries the modern allergy caveat noted above); restlessness and poor sleep, including in children.

*Mawāneʿ / Iḥtirāzāt (contraindications):* hot/bilious (_ṣafrāwī_) temperaments in quantity, per the Hot mizāj; *pregnancy*, on the emmenagogue attribution; the modern Asteraceae-sensitization caution, which has no classical correlate and is flagged as modern.

*Muṣliḥ (corrective):* classical practice tempers warming aromatics of this class with a cooling-moistening adjuvant — *rose-water (ʿarq-i gulāb)*, gum tragacanth (_kathīrāʾ_), or a little honey are the pairings named for the warm-aromatic class generally. *Badal (substitute):* other mild warm aromatics of the same register — *marzanjūsh* (marjoram-class, cf. `oregano.typ`), *shabath* (dill), *anīsūn* (anise, see `anise.typ`). *Flagged:* I have *not* confirmed a _muṣliḥ_/_badal_ pairing named specifically for bābūnaj in the formal classical _badal_ tables; the pairings above are the class-level conventions, and the specific entry should be verified against Ibn al-Bayṭār's _al-Jāmiʿ_ and the Unani _badal_ literature rather than taken from this entry as textually fixed.

*Ṭibb al-Nabawī attestation:* *none proper.* Chamomile is a *Greco-Arabic (Dioscoridean) and Mediterranean-folk* drug with no Qurʾānic verse and no sound-hadith attestation; I flag this rather than manufacture a pedigree, as with sage. Its ubiquity in Muslim-world household practice is cultural and Tibb-pharmacological, not Prophetic-medical.#footnote[No Qurʾānic or sound-hadith attestation for بابونج; its standing is Greco-Arabic pharmacological and folk-domestic. Flagged explicitly so that the herb's ubiquity across the Muslim world is not retrospectively read as Ṭibb al-Nabawī provenance — the same honesty point made for sage in `sage.typ`.]

== Classical Formulas & Preparations

=== Chinese medicine (中醫)

*No classical Chinese formula uses chamomile.* Modern Chinese use of 洋甘菊 is a post-classical Western-derived import (herbal-tea and aromatherapy registers), and the 微寒 property commonly assigned to it in modern Chinese popular sources is the naming artefact flagged above. The classical Chinese flower-drug formulas belong to *菊花* — *桑菊飲 (Sāng Jú Yǐn)* for wind-heat, *杞菊地黃丸 (Qǐ Jú Dì Huáng Wán)* for Liver-Kidney yin vacuity with eye signs — and are noted here *only to keep the disambiguation sharp*; they have nothing to do with chamomile. See `chrysanthemum.typ`.

=== Ayurveda

*No classical Ayurvedic formula uses chamomile* (post-classical introduction). Where it appears in modern Indian herbal commerce it does so under the Unani-derived name *babūnā* and within Unani rather than Ayurvedic formulation logic; modern Ayurveda-adjacent products slot it into the _nidrā-janana_ and _śūla-praśamana_ registers by extension — reasoned, not classical.

=== Western / Greco-Roman and later European medicine

*The deepest and most continuous tradition for this herb, and the one that carries it into modern regulated phytotherapy.*

- *Greco-Roman:* *Dioscorides* (_De Materia Medica_ III) treats the _anthemis_/_chamaímēlon_ kinds as emmenagogue, lithontriptic, and resolvent, and for liver obstruction — with the species-identification caveat noted above. *Pliny* (_Naturalis Historia_ XXII) continues the register. *Galen* classes chamomile *warm and drying*, and the *chamomile-infused oil* (_ἔλαιον χαμαιμήλινον_; Latin _oleum chamomillae_) is a standard Galenic *resolvent and analgesic topical* — the direct ancestor of the European macerated chamomile oil still sold today, and a form distinct from the steam-distilled blue essential oil (which is a post-medieval product of distillation technology).
- *Medieval:* *Hildegard von Bingen* (_Physica_, 12th c.) treats chamomile for digestive and intestinal complaints; the herb is a fixture of monastic-garden and later officinal pharmacy as _Flores Chamomillae_.
- *Early modern / officinal:* *Culpeper* (_The English Physician_) and *Gerard* (_Herball_) give it extensive entries; British pharmacy standardized on *Roman* chamomile (_Anthemidis flores_, _Infusum Anthemidis_) as a bitter stomachic and in fomentations, while continental — especially German — pharmacy standardized on *German* chamomile. The *chamomile fomentation and poultice* for colic, swellings, and toothache, the *chamomile gargle and mouthwash*, the *sitz bath*, and the *steam inhalation* are all long-continuous preparations.
- *Modern regulated phytotherapy — the strongest dossier in this entry:* the German *Commission E* monograph approves chamomile flower for *gastrointestinal spasm and inflammatory conditions* (internally) and for *inflammation of the skin and mucous membranes*, including the respiratory tract (externally/inhalation); the *EMA/HMPC* monograph on _Matricaria recutita_ flos carries well-established and traditional-use indications for mild GI complaints, for minor skin inflammation, and for inhalation in catarrh. The long-marketed German *Kamillosan* preparations and the *chamomile mouthwash* protocols for oral mucositis belong to this register.#footnote[Greco-Roman: Dioscorides, _De Materia Medica_ III (Beck translation); Pliny, _Naturalis Historia_ XXII (Loeb); Galen, _De simplicium medicamentorum facultatibus_ (warm-and-drying classification; the chamomile oil). Medieval/early-modern: Hildegard von Bingen, _Physica_; Culpeper, _The English Physician_; Gerard, _Herball_; Evans, _Trease and Evans' Pharmacognosy_ for the officinal _Anthemidis_/_Chamomillae_ preparations and the British-Roman vs. German-German pharmacy split. Modern: Blumenthal (ed.), _The Complete German Commission E Monographs_ (American Botanical Council, 1998); EMA/HMPC monograph and assessment report on _Matricaria recutita_ L., flos — verify against the current revision.]

=== Tibb (Arabic-Islamic)

Covered above: *bābūnaj* as *mufattiḥ*, *muḥallil*, *musakkin*, and mild *munawwim*. The constitutive living preparations are the *مغلي (maghlī)* — simple hot infusion, the everyday form from the Maghreb through the Levant to South Asia; the *عرق بابونج (ʿarq bābūnaj)* hydrosol/distillate of the Unani _ʿarq_ class; *حمام / كمادة (ḥammām / kimāda)* — the chamomile bath and hot fomentation for joint pain and swellings, one of the oldest and most consistently attested Tibb applications; and chamomile as a warming-resolvent component in compound *maʿjūn* and *jawārish* digestive electuaries. The *roghan-i bābūnah* (chamomile oil) of the Unani _roghan_ class continues the Galenic infused-oil form directly.

== Climate, Constitution & Regional Diet

_M. chamomilla_ is a *pan-temperate* annual — native across Europe, West Asia, and North Africa, naturalized and cultivated worldwide, and *genuinely not confined to one climatic register* in the way sage is confined to warm-dry Mediterranean slope or oats to cool-damp Atlantic. Its two substantive traditional homes are the *warm-dry Mediterranean/Levantine* zone (the Greco-Roman and Tibb register) and *cool-temperate continental Europe* (the German/Slavic _Kamille_ register, where most of the modern clinical tradition was built). See `climates.typ`.

=== Warm-dry Mediterranean and Levantine (the Greco-Roman and Tibb home)

Dry-summer, cool-wet-winter hills and field-margins (Köppen Csa/Csb). Constitutionally the summer carries Pitta and external 燥/熱; the winter carries cool-damp Vāta-Kapha. *Traditional preparation and cares.* The constitutive forms are the *hot maghlī infusion* after heavy or oily meals, the *fomentation and bath* for joint and abdominal pain, and the *infused oil* — i.e. the *warming-resolvent* uses, climatically apt to the cool-damp winter and to cold-pattern digestion rather than to high summer. The classical _muṣliḥ_ convention (rose-water, a little honey) is the tradition's own correction for the Hot mizāj in hot constitutions and hot seasons; it is constitutive, not decorative.

=== Cool-temperate continental Europe (the German/Slavic Kamille register — the modern clinical home)

Köppen Cfb/Dfb. External 寒濕 and seasonal Vāta-Kapha loading; cold-pattern digestion and respiratory catarrh are the characteristic burdens. *Traditional preparation and cares.* The *hot Kamillentee* taken freely, the *steam inhalation* for catarrh, and the *compress* for skin inflammation are the constitutive forms — all of them *hot and moist in application*, which is the climatically apt delivery for a cold-damp zone. That this cool-damp-climate register, not the Mediterranean one, is where chamomile's modern clinical and regulatory tradition was built (Commission E, Kamillosan) is a notable case of a herb's *scientific* centre of gravity settling outside its classical-textual one.

=== Hot-humid tropical and subtropical (Brazil and the Lusophone diffusion)

Köppen Af/Am/Cfa. External 濕熱; Pitta-Kapha loading; Spleen and Heart carry the burden per `climates.typ`. Chamomile is *not indigenous* here and has no classical register; its presence is *post-classical trade diffusion* of the dried flower, now thoroughly domesticated as *chá de camomila*. The preparation that travelled is the *hot infusion*, used chiefly for *infant colic, agitation, and sleep* — and notably, the indications that travelled are the *antispasmodic and calmative* ones rather than the Mediterranean warming-digestive-after-fatty-meals register. Taken hot in a hot-humid climate the warming note is mildly counter-climatic; in practice the dose is small, the drug is gentle, and the Brazilian register often blends it with *erva-cidreira* and *maracujá* (cooling-calming companions, see the glossary), which functions as an unwitting _muṣliḥ_.

=== Climates where chamomile is not traditional

Cold-dry high-altitude (Tibetan/Himalayan/Central Asian) and sub-Arctic zones have no indigenous chamomile tradition; the herb's spread there is modern and commercial. The *indications* travel freely — colic and sleeplessness are climate-independent — but the plant's constitutional homes are the two temperate zones above.

=== Modern transposition (_deśa-viruddha_ / _kāla-viruddha_, Caraka Sūtra 26)

Chamomile is one of the *least problematic* cross-climate transpositions in this book: it is mild, taken in small doses, and its principal indications are not climate-specific. The genuine transposition issues are of *form and register* rather than geography. First, *form*: the modern *essential-oil* and *concentrated-extract* registers (including the Roman-chamomile oil) concentrate the drug far outside the traditional infusion-and-fomentation context, and carry the allergy and pregnancy cautions at a different order of magnitude — a _mātrā-viruddha_ problem, not a _deśa_ one. Second, *register*: the popular reassignment of chamomile as a *cooling* herb — in Western wellness writing and, via the 洋甘菊 name, in modern Chinese sources — detaches it from the Hot-Dry mizāj that governed its classical pairing rules, so that the tradition's own _muṣliḥ_ logic (rose-water, honey, cooling companions in hot constitutions) is lost precisely where it would be useful. Seasonally, the warming-resolvent uses suit cool/damp seasons and cold-pattern digestion more than high summer in hot constitutions (the _kāla-viruddha_ parallel). See `climates.typ`.

== Modern Nutrition & Pharmacology

Chamomile is a *medicinal-culinary flower*, consumed as infusion, extract, oil, or topical preparation in small amounts; it is not a nutritive food and no per-100 g macronutrient profile is meaningful. Its interest is the essential oil, the flavonoids, and the mucilage polysaccharides.

*Key constituents (German chamomile, dried flower):*
- *Essential oil (~0.3–1.5%)* — *α-bisabolol* and the *bisabolol oxides A/B* (the principal anti-inflammatory and antispasmodic terpenoids; chemotype-dependent in ratio); *chamazulene* — the *deep blue* sesquiterpene formed *during steam distillation* from the colourless proazulene *matricin*, so that the fresh flower and the infusion are not blue but the distilled oil is, a classic and visually memorable phytochemistry fact; *en-yn-dicycloethers (spiroethers)* — potent smooth-muscle antispasmodics; *farnesene*.
- *Flavonoids* — *apigenin* and especially *apigenin-7-O-glucoside* (the dominant flavonoid, and the constituent carrying the anxiolytic/sedative mechanism), *luteolin*, *quercetin*, *patuletin* glycosides.
- *Coumarins* — *herniarin*, *umbelliferone* (basis of the theoretical anticoagulant interaction).
- *Mucilage polysaccharides (~10%)* — demulcent; relevant to the topical and mucosal uses.
- *Roman chamomile differs substantially*: higher in *angelate and isobutyrate esters*, much lower in chamazulene and apigenin — which is why the two species are not pharmacologically interchangeable, and why allergy reports cluster differently between them.#footnote[Phytochemistry (α-bisabolol and oxides; matricin → chamazulene on distillation; spiroethers; apigenin-7-O-glucoside; herniarin/umbelliferone; ~10% mucilage) and the German/Roman compositional contrast: Evans, _Trease and Evans' Pharmacognosy_; EMA/HMPC assessment report on _Matricaria recutita_ flos; standard phytochemistry reviews — verify against current literature.]

*Pharmacology of note:*
- *Antispasmodic (smooth muscle) — the best-mechanized action.* Bisabolol and the *spiroethers* relax intestinal smooth muscle in vitro with a papaverine-like profile; this grounds the colic, griping-pain, and menstrual-cramp uses across all four traditions treated here, and is the pharmacological core of the Commission E GI-spasm approval.
- *Anti-inflammatory.* Bisabolol, chamazulene, and apigenin show anti-inflammatory activity in standard models; topically, a long-marketed chamomile preparation has been compared against low-potency hydrocortisone in dermatitis trials with broadly comparable results in some studies — *modest and not uniformly replicated*, and flagged accordingly.
- *Anxiolytic — apigenin at the GABA-A benzodiazepine site.* Apigenin is a *partial agonist/ligand at the benzodiazepine binding site of the GABA-A receptor* in vitro, the leading proposed mechanism. Clinically, a *standardized-extract RCT series (Amsterdam et al.)* reported a modest anxiolytic effect in generalized anxiety disorder, with a later relapse-prevention trial giving weaker results — *a real but modest signal, not established first-line anxiolytic therapy*; flagged.
- *Sleep.* Traditional and near-universal; modern trial evidence for measurable sleep-quality improvement is *weak-to-modest*, and the popular reputation substantially outruns the data — flagged, per this book's standard on over-claimed herbal effects.
- *Infant colic.* The widely cited trials used *multi-herb preparations* (chamomile with fennel, lemon balm, and others), so the effect *cannot be attributed to chamomile alone* — an important honesty point given how often the trials are reported as "chamomile for colic."
- *Oral mucositis.* Chamomile mouthwash has modest supporting evidence for chemotherapy-induced mucositis; consistent with the mucilage-plus-anti-inflammatory profile.
- *Antimicrobial, glycemic, lipid.* Modest in vitro and small-trial signals; not clinically established.#footnote[Mechanisms and clinical evidence: spiroether/bisabolol antispasmodic activity and the apigenin GABA-A benzodiazepine-site interaction are standard in the pharmacology literature; Amsterdam et al., chamomile-extract RCTs for generalized anxiety disorder (and the subsequent relapse-prevention trial with weaker results); topical comparison trials of chamomile preparations vs. low-potency corticosteroid; mucositis mouthwash trials; the multi-herb composition of the infant-colic trials. All flagged by evidence tier — verify against current systematic reviews. The gap between chamomile's popular reputation as a sleep aid and the trial evidence is noted deliberately.]

*Safe daily dosage / upper limit:* chamomile has *no toxicological ceiling at infusion dose* — the limiting considerations are *allergy* and *preparation concentration*, not cumulative toxicity (contrast sage and wormwood, where thujone sets a hard ceiling).
- *Infusion (German chamomile flower):* ~*1–4 g* dried flower per cup, up to *3–4×/day* (the Commission E range); suitable for continuous ordinary use.
- *Topical / fomentation / bath:* standard preparations per the Commission E and EMA external-use indications; *eye-washes are best avoided* given the conjunctival-sensitization reports.
- *Essential oil and concentrated extracts:* a different register — small doses, not for internal self-administration, and the pregnancy and allergy cautions apply with greater force.
- *Contraindicated / avoid:* known *Asteraceae (Compositae) allergy*; concentrated extracts and essential oil in *pregnancy*.
- *Cautions:* anticoagulant therapy (theoretical, coumarins); additive sedation with sedative drugs and alcohol; infants — widely used traditionally, but check current national pediatric guidance, and note that *honey used to sweeten an infant's infusion carries its own infant-botulism contraindication* (see `honey.typ`).
- *Reference thresholds, not personalized medical advice* — ordinary chamomile tea is among the safest herbal preparations in this book; concentrated forms, the essential oil, pregnancy, and Asteraceae-sensitized individuals warrant care.#footnote[Dosing and safety: Blumenthal (ed.), _The Complete German Commission E Monographs_; EMA/HMPC monograph on _Matricaria recutita_ flos (internal and external indications and posology); Asteraceae cross-reactivity and the conjunctival/eye-wash reports: current allergy literature. Reference thresholds requiring current verification, not medical advice.]

== Sources

- Dioscorides, _De Materia Medica_ III (Beck translation, Olms-Weidmann, 2005); Pliny, _Naturalis Historia_ XXII (Loeb); Galen, _De simplicium medicamentorum facultatibus_ (warm-dry classification; _oleum chamomillae_).
- Hildegard von Bingen, _Physica_; Culpeper, _The English Physician_; Gerard, _Herball_; Evans, _Trease and Evans' Pharmacognosy_ (officinal _Chamomillae_/_Anthemidis_ preparations; phytochemistry).
- Ibn Sīnā, _al-Qānūn fī al-Ṭibb_ II (بابونج); Ibn al-Bayṭār, _Kitāb al-Jāmiʿ li-Mufradāt al-Adwiya_; AYUSH/CCRUM, _National Formulary of Unani Medicine_; _Khazāyin al-Adwiya_.
- Blumenthal (ed.), _The Complete German Commission E Monographs_ (American Botanical Council, 1998); EMA/HMPC monograph and assessment report on _Matricaria recutita_ L., flos — verify against current revision.
- Amsterdam et al., chamomile-extract RCT series for generalized anxiety disorder, and the subsequent relapse-prevention trial; topical chamomile vs. corticosteroid comparison trials; oral-mucositis mouthwash trials; multi-herb infant-colic trials — all verify against current systematic reviews.
- Liddell & Scott, _A Greek–English Lexicon_ (χαμαί, μῆλον, χαμαίμηλον); Lewis & Short, _A Latin Dictionary_ (_matrix_, _chamomilla_); _Oxford English Dictionary_ (camomile/chamomile); Lane, _An Arabic-English Lexicon_ (بابونج); Grieve, _A Modern Herbal_ (1931).
- Bensky, Clavey & Stöger, _Materia Medica_, 3rd ed. — cited only to enforce the 菊花-vs-chamomile disambiguation.
- Foundational and sibling frameworks: `tibb-al-arabi.typ`, `climates.typ`, `zz-glossary.typ`; the deliberately-distinguished Chinese Asteraceae entry `chrysanthemum.typ`; the parallel reasoned-only European-herb entries `sage.typ`, `oregano.typ`; the shared μῆλον root in `apple.typ`; the Tibb-bābūnaj framework extension in `lucera.typ`; the infant-honey caution in `honey.typ`.
