= Tilapia

_Scope: this entry treats the farmed and wild tilapias of the family Cichlidae — principally *Oreochromis niloticus* (L.), Nile tilapia, the dominant aquaculture species, with *O. aureus*, *O. mossambicus*, and the Galilean *Sarotherodon galilaeus*. A species-level entry satellite to fish.typ, which carries the cross-cutting matsya / samak / Bencao-fish frameworks that this entry applies rather than restates; parallel in role to salmon.typ and sardines.typ, though given the full template here, since the Classical Formulas and Climate sections are permanent in this book and tilapia has substantive material for both. Status: an unusual split. The species is *not* named in any of the three Eurasian pharmacological canons — but unlike salmon (a cold-water fish genuinely beyond medieval reach), Nile tilapia lived in the *heartland* of two of them: it is among the most frequently depicted animals in dynastic Egyptian religious art, and it swims in the Sea of Galilee, so its absence from classical pharmacology is an absence of *species-specific monographs*, not of contact — the generic Tibb *samak al-nahr* category covered it as a matter of course in medieval Egypt. Against that ancient background sits a radically modern story: introduced to China in 1957, to Brazil in the 1970s–80s, and now the most farmed freshwater fish on earth after the carps, the "aquatic chicken" of global protein. Ancient-Egyptian and Galilean registers are treated as genuine historical-religious attestation, explicitly *not* as pharmacological canon._

== Nomenclature & Etymology

*Species and taxonomy:* "tilapia" is a *trade category* covering several cichlid genera, split in 20th-c. revision according to *reproductive mode* — a taxonomic criterion that happens to track the very behaviour behind the fish's ancient symbolism:
- *_Oreochromis niloticus_ (L.)* — *Nile tilapia*; ~75% of global farmed tilapia; a *maternal mouthbrooder* (the female incubates eggs and then fry in her buccal cavity). Native range: the Nile basin, the Rift lakes, West Africa, and the Levantine Jordan system.
- *_Oreochromis aureus_* (blue tilapia), *_O. mossambicus_* (Mozambique tilapia) — secondary farmed species, and the principal invasive ones; extensively hybridized in aquaculture.
- *_Sarotherodon galilaeus_* (Artedi) — *Galilee tilapia*; biparental/paternal mouthbrooder; the principal tilapia of Lake Kinneret and the species most often (though not certainly) behind the commercial "St. Peter's fish."
- *_Coptodon zillii_* (= _Tilapia zillii_) — redbelly tilapia; a *substrate-spawner*, retained in _Tilapia_ sensu stricto after the mouthbrooding genera were separated into _Oreochromis_ (maternal) and _Sarotherodon_ (paternal/biparental).
*All are African and Levantine in origin*; the global distribution is entirely a product of 20th-c. aquaculture transfer.#footnote[Trewavas, E. (1983), _Tilapiine Fishes of the Genera Sarotherodon, Oreochromis and Danakilia_ (British Museum, Natural History) — the standard revision, splitting the old genus _Tilapia_ by brooding mode; FAO aquaculture statistics for species shares. Hybridization in commercial stocks is extensive enough that market "tilapia" is frequently of mixed parentage — relevant to composition figures below.]

*Genus and English name:* *_Tilapia_* was coined by the Scottish zoologist *Andrew Smith* (1840), Latinizing a *Tswana (Setswana)* word for fish — *thiape* / plural *ditlhapi*. It is one of the very few genus names of *Southern African Bantu origin* in standard global zoological use, and the English common name is simply the genus name in ordinary speech.#footnote[Smith, A. (1840), _Illustrations of the Zoology of South Africa_; the Setswana _thiape_/_ditlhapi_ etymology is the standard account in ichthyological reference works and in FishBase's etymology note for _Tilapia_ Smith, 1840.]

*Ancient Egyptian — the deepest "classical" register for this fish, though not a medical one.* The Nile tilapia (*in.t* in Egyptological transliteration of one of the common fish-words; modern Egyptian Arabic *bulṭī*) is among the *most frequently represented animals in dynastic Egyptian art* — in tomb painting, faience amulets, cosmetic palettes, jewellery, and ceramic decoration from the Predynastic period onward. The reason is almost certainly *mouthbrooding*: the emergence of a cloud of live fry from an adult's mouth read naturally as an image of *self-generation, renewal, and rebirth*, and the fish accordingly carries solar-rebirth symbolism and associations with *Hathor* and *Hesat*, appearing on funerary objects where regeneration is the point. *A flagged identification caveat:* the equation of the mythological *Abdju / Abtu fish* (the fish said to swim before the solar barque of Ra, warning it of the serpent Apophis) with tilapia *specifically* is a long-standing but *contested* Egyptological identification — hieroglyphic fish determinatives are often not species-diagnostic, and other Nile fish (_Lates niloticus_, Nile perch; _Mormyrus_ spp.) are preferred by some specialists for particular textual occurrences. *The tilapia-as-rebirth reading for the mouthbrooding iconography is well established; the Abtu identification is the leading hypothesis, not a settled fact.* And in all cases this is *religious and symbolic* attestation, not pharmacological: Egyptian medical papyri (Ebers, Hearst) are not the source of these fish depictions, and this entry does not claim a dynastic-Egyptian drug monograph.#footnote[Houlihan, P. F., _The Animal World of the Pharaohs_ (Thames & Hudson, 1996) — standard synthesis of Egyptian fish iconography and the tilapia/rebirth association; Gamer-Wallert, I., _Fische und Fischkulte im alten Ägypten_ (Wiesbaden, 1970) — the foundational monograph on Egyptian fish cult; both discuss and qualify the Abtu identification. Species identification in Egyptian iconography and texts is inherently uncertain and contested among specialists — flagged. The register is religious-symbolic, not medical.]

*Modern Egyptian Arabic:* *بلطي (bulṭī)* — the standard name; tilapia is today *the most consumed fish in Egypt*, both from the Nile and Delta lakes and from a very large aquaculture sector, and *samak bulṭī mashwī* (grilled tilapia) is an everyday dish. Whether the modern name descends from an ancient Egyptian form is not established here and should not be assumed.

*Hebrew and Levantine Arabic — the "St. Peter's fish" register:* Hebrew *אמנון (amnun)*; Levantine Arabic *مشط (mushṭ,* "comb," for the long comb-like dorsal fin). The commercial name *"St. Peter's fish"* — applied in Israel chiefly to *Sarotherodon galilaeus* from Lake Kinneret and served fried whole to pilgrims and tourists — alludes to *Matthew 17:24–27*, where Peter is told to catch a fish and find in its mouth a coin for the Temple tax; the mouthbrooding habit (a tilapia will hold objects in its buccal cavity) makes the association irresistible. *Flagged clearly:* the Gospel text *names no species*; the identification is modern, popular, and commercially useful, and is *not* an exegetical, rabbinic, or patristic tradition. Tilapia does, separately, satisfy the *kashrut* fins-and-scales rule (Leviticus 11:9–12) and is farmed and eaten as kosher fish in Israel — that much is a genuine religious-dietary fact rather than a legend. See `fish.typ` for the dietary-law framework.#footnote[Matthew 17:24–27, Greek New Testament; standard commentaries note the silence on species. The "St. Peter's fish" trade name for Kinneret tilapia is documented modern Israeli culinary-and-tourism history (Nathan, J., _The Foods of Israel Today_, 2001; Galilee fisheries literature), not a classical textual tradition — flagged. Kashrut fins-and-scales rule: Leviticus 11:9–12; Deuteronomy 14:9–10.]

*Chinese:* *罗非鱼 / 羅非魚 (luófēiyú)* — a phonetic transliteration of "tilapia"; also *福寿鱼 (fúshòuyú,* "fortune-and-longevity fish"), an auspicious market name adopted after introduction. *Introduction history:* *O. mossambicus* arrived in 1957 (via Vietnam) and *O. niloticus* in 1978, the latter through a US–China aquaculture exchange in the post-normalization period; China is now the world's largest producer and exporter. *There is no Bencao entry*: 罗非鱼 postdates the _Bencao Gangmu_ (1578) by four centuries and appears in no classical pharmacopoeia, so any Chinese-medical placement is reasoned extension from the classical freshwater-fish drugs (*鯽魚*, *鯉魚* — see `fish.typ`), not text.#footnote[Introduction dates and production: FAO aquaculture country reports for China and Chinese aquaculture-history literature; the 1978 _O. niloticus_ introduction via a US–China exchange is documented in that literature. Absence from _Bencao Gangmu_ (1578) and earlier pharmacopoeias is definitional — the species was not in China.]

*Japanese:* *ティラピア (tirapia)*; also the market name *イズミダイ (izumidai,* "spring sea-bream") — a *euphemistic trade name* under which tilapia has been sold in Japan as a substitute for sea bream, a naming practice worth recording because it illustrates how thoroughly tilapia functions as a *generic white-fish commodity* rather than a culturally situated food.

*Portuguese:* *tilápia*; *tilápia-do-nilo* for _O. niloticus_. *Brazil* is now among the largest producers globally; cage culture in reservoirs (Paraná, São Paulo, the São Francisco system) and tank systems expanded rapidly from the 1990s, and tilapia has *overtaken native species in Brazilian farmed-fish volume*. *Tilápia na brasa*, *filé de tilápia*, and *tilápia frita* are now standard in inland Brazilian cooking, where the fish's low price and mild flavour substitute for coastal marine species. *Ecological caution, stated plainly:* escaped and deliberately stocked tilapia behave as an *invasive species* in Brazilian natural waters, competing with and in documented cases displacing native fish; this is a live conservation and policy concern, distinct from the fish's dietary merits and not resolved by them.#footnote[Brazilian production and the overtaking of native species in farmed volume: FAO statistics and Embrapa Pesca e Aquicultura reports. Invasive-species impacts of _O. niloticus_ in Brazilian natural waters: Brazilian ichthyological and conservation literature; verify against current ICMBio/IBAMA assessments. Noted as a genuine ethical/ecological consideration rather than folded into the nutritional appraisal.]

*Sanskrit:* *no name, classical or otherwise* — the fish is African-Levantine and reached South Asia only through 20th-c. aquaculture introduction (it is now farmed in India and Bangladesh). The general category *मत्स्य (matsya)* applies; see the Ayurveda section and `fish.typ`.

== Classical Chinese Medicine (中醫) View

_No classical entry — 罗非鱼 is a 20th-c. introduction, absent from the entire Bencao tradition (see Nomenclature). The reading below is reasoned extension, anchored specifically on_ 鯽魚 (jìyú, crucian carp) _— the classical Chinese freshwater-fish drug tilapia most closely resembles in habitat, body form, flesh character, and culinary role — rather than on fish in general. Flagged, not canonical._

*Property (by reasoned extension):* Neutral (平), tending slightly warm (微溫) when cooked with warming aromatics — following 鯽魚, which classical sources give as neutral (平) or slightly warm.

*Flavor:* Sweet (甘).

*Channels (by extension):* Spleen (脾), Stomach (胃); Large Intestine (大腸) in the 鯽魚 register for its use in chronic diarrhoea.

*Actions (by extension):*
- *健脾和胃 (jiàn pí hé wèi)* — strengthens the Spleen and harmonizes the Stomach: the primary reasoned action, following 鯽魚's classical use as a gentle, easily digested, convalescent-and-recovery food-drug. Tilapia's very mild, lean, easily digested flesh fits this register well.
- *利水消腫 (lì shuǐ xiāo zhǒng)* — promotes urination and reduces swelling: 鯽魚 is classically used in edema and, specifically, in the *rice-and-crucian-carp soups* given for postpartum and nutritional edema. Reasoned for tilapia by direct analogy.
- *通乳 (tōng rǔ)* — promotes lactation: the classical *鯽魚湯 (jìyú tāng,* crucian carp soup) is one of the best-known Chinese postpartum galactagogue foods, and tilapia soup is used identically in modern Chinese households — a *living folk substitution* of the new fish into an old classical slot, which is exactly how a non-canonical food acquires a traditional role, and is worth noting as process rather than as attestation.
- *補虛 (bǔ xū)* — supplements vacuity: generic lean-protein convalescent nourishment.

*Cautions (by extension):* the classical fish cautions apply — damp-heat and sores/skin-disease patterns (fish being classically regarded as *發物, fāwù*, "provoking foods" that can aggravate latent skin and inflammatory conditions, a folk-clinical category still widely observed in Chinese practice); no classical 配伍禁忌 exists for a drug with no classical entry.#footnote[Reasoned placement anchored on 鯽魚 (crucian carp): sweet, neutral, Spleen/Stomach, 健脾利水 and the 鯽魚湯 lactation use — see the classical fish drugs catalogued in `fish.typ` and Li Shizhen, _Bencao Gangmu_ (1578), fish section; Bensky, Clavey & Stöger, _Materia Medica_, 3rd ed. The 發物 ("provoking food") category is a living folk-clinical rather than strictly textual one — flagged. The substitution of tilapia into the 鯽魚湯 postpartum slot is observed modern practice, not classical text.]

== Ayurvedic Dravyaguna (द्रव्यगुण)

_Reasoned analysis within a classical category. There is no species-specific attestation — tilapia reached India only through 20th-c. aquaculture — but unlike a plant with no analogue, fish_ as such _is a developed classical category: *मत्स्य (matsya)*, treated in Caraka Sūtrasthāna 27 (annapānavidhi) and Suśruta Sūtrasthāna 46, with sub-classification by habitat. Tilapia falls under *नादीमत्स्य (nādī-matsya)*, riverine/freshwater fish. The reading below applies the classical matsya parameters, with one honest flag: the classical attributions were built on the fish the saṃhitā authors knew, and a *lean, farmed, pellet-fed cichlid fits them imperfectly* — see the guṇa note._ See `fish.typ`.

*Rasa (classical, for matsya):* Madhura (मधुर, sweet).

*Guṇa (classical, with a flag):* Guru (गुरु, heavy), Snigdha (स्निग्ध, unctuous). *The flag:* this attribution describes oily, fatty fish — and tilapia is among the *leanest* commonly eaten fish (~2.7 g fat/100 g; see Modern Pharmacology). A consistent reading would attenuate *snigdha* considerably and class farmed tilapia as *laghu-tara* (lighter) than the classical matsya norm, nearer the saṃhitās' own acknowledgement that fish vary. *Flagged as a case where applying a classical category to a modern substance strains the category* — the more honest outcome than silently reproducing "guru-snigdha" for a lean fillet.

*Vīrya:* Uṣṇa (उष्ण, heating) per the dominant classical reading — *with a genuine cross-system divergence to note*: the saṃhitās class fish as *uṣṇa*, while classical Tibb classes fresh fish as *Cold and Moist* (see the Tibb section and `fish.typ`). The two great humoral systems disagree squarely about fish, and this book does not average them. Some Ayurvedic commentaries additionally class certain freshwater species as *śīta*, which complicates the picture further.

*Vipāka:* Madhura (मधुर, sweet).

*Prabhāva:* *None assigned, and the classical texts assign none to matsya* — the actions of fish follow directly from madhura rasa, guru-snigdha guṇa, uṣṇa vīrya, and madhura vipāka, and no distinct prabhāva-level action is named. *Stated explicitly rather than invented*, per this book's Prabhāva rule.

*Doṣa effect:* *Vāta-śāmaka* (the governing effect — madhura-guru-snigdha-uṣṇa is the classic Vāta-pacifying combination, which is why fish is a convalescent food in the Vāta-depleted); *Kapha-vardhaka* and *Pitta-vardhaka* (heavy-unctuous aggravates Kapha; heating aggravates Pitta). Hence the classical unsuitability of fish in inflammatory, suppurative, and skin conditions — converging precisely with the Chinese *發物* caution above.

*Karma:* _Balya_ (strengthening); _bṛṃhaṇa_ (nourishing, anabolic); _vṛṣya_ / _śukrala_ (aphrodisiac, generative-tissue-promoting — fish is the canonical _vṛṣya_ flesh-food of the saṃhitās); _hṛdya_ (cardiotonic); used in _vāta-vyādhi_ and convalescent depletion. For tilapia specifically, the lean profile makes it a *better fit for the balya/convalescent register than for the bṛṃhaṇa/fattening one*.#footnote[Matsya in Caraka Saṃhitā, Sūtrasthāna 27 (_annapānavidhi_, fish section) and Suśruta Saṃhitā, Sūtrasthāna 46; Bhāvaprakāśa Nighaṇṭu, _Māṃsa-varga_; translations Sharma & Dash (Chowkhamba), Murthy. The nādī-matsya (riverine) sub-classification and its classical reading as the heavier type: same sources. The flag on applying guru-snigdha to a lean farmed fish is this entry's own observation, marked as such. The uṣṇa-vs-Tibb-Cold divergence is treated in `fish.typ` and is not reconciled here.]

=== Viruddha (विरुद्ध — incompatibilities)

_(tags: S core saṃhitā, N later nighaṇṭu, F folk/regional, M modern/pharmacological)_

- *(S) Matsya + kṣīra (fish + milk)* — *the most-cited saṃyoga viruddha in the entire Ayurvedic canon*, held to cause _rakta-duṣṭi_ (blood pathology) and _kuṣṭha_ (skin disease); Caraka Sūtrasthāna 26. It applies to tilapia without species qualification. *A notable cross-system convergence:* Avicenna independently forbids fish with milk in the _Qānūn_ — two traditions arriving at the same specific prohibition. No modern toxicological basis has been established, and this book records the convergence without endorsing a mechanism.
- *(S/N) Other classical fish combinations* — fish with curd, and with certain sour fruits, are cautioned in some sources; _virodha_ by _vīrya_ (opposing potencies) is the usual rationale.
- *(S/N) Conditional* — contraindicated in Pitta-inflammatory states, _kuṣṭha_ (skin disease), suppuration, and damp-heat patterns; converges with the Chinese *發物* category.
- *(F) Folk/regional* — Brazilian, Egyptian, and Chinese household practice pairs tilapia with acidic and aromatic correctives (lime, lemon, vinegar, coriander, cumin), which is the *muṣliḥ* logic of the Tibb tradition arrived at by cooking rather than by doctrine; noted as (F)-tier living practice.
- *(M) Modern / pharmacological:*
  - *Mercury — low, and this is a genuine advantage.* Farmed tilapia is short-lived, low on the trophic chain, and pellet-fed; it is consistently placed in the *lowest-mercury* category (FDA/EPA "Best Choices"), appropriate in pregnancy and childhood. See `fish.typ`.
  - *Omega-6 : omega-3 ratio — the real controversy, properly framed.* A widely cited 2008 study (Weaver et al., _Journal of the American Dietetic Association_) reported that farmed tilapia's fatty-acid profile is high in arachidonic acid relative to long-chain omega-3, and framed its "inflammatory potential" unfavourably against bacon and hamburger — a comparison that generated years of popular-press alarm. *What is true:* the ratio finding is real and is a direct consequence of *corn-and-soy-based commercial feed*, so it is *farm-and-feed-dependent, not an intrinsic property of the species*. *What is overstated:* the bacon comparison concerned a ratio, not total saturated fat, sodium, or processing, and tilapia remains a lean, low-mercury, high-protein food; subsequent reviews have taken a more qualified view. *Both halves of that belong in the record.*
  - *Low long-chain omega-3* — ~0.1–0.2 g EPA+DHA/100 g, an order of magnitude below salmon or sardines. Tilapia therefore does *not* deliver the cardiovascular and neurodevelopmental benefit specifically attributed to oily fish; it should not be counted as an oily-fish serving.
  - *Farmed-sourcing issues* — antibiotic use, water quality, and feed standards vary widely by producer and country; ASC and comparable certification provides meaningful (not absolute) assurance. A *sourcing* problem, not a species toxicity.
  - *Allergy* — fish allergy (parvalbumin-mediated) applies, with cross-reactivity across species common.
  - *Purines / gout* — moderate; lower than sardines and anchovies, relevant only in gout-susceptible individuals.#footnote[Fish-milk viruddha: Caraka Saṃhitā, Sūtrasthāna 26 (_viruddhāhāra_); the Avicennan parallel prohibition: Ibn Sīnā, _al-Qānūn_ II, samak entry — convergence noted in `fish.typ`. Mercury category: FDA/EPA "Best Choices" advice on fish consumption. Fatty-acid controversy: Weaver, K. L. et al. (2008), "The content of favorable and unfavorable polyunsaturated fatty acids found in commonly eaten fish," _Journal of the American Dietetic Association_ — verify authorship and current citation; subsequent reviews offer a more qualified reading, and the feed-dependence of the finding is the key qualification. Aquaculture antibiotic and certification issues: current ASC/FAO sources.]

== Traditional Arabic & Islamic Medicine (Ṭibb al-ʿArabī wa-l-Islāmī / Unani)

_A middle case, and the most interesting scope question in this entry. Tilapia is not a species-specific drug in classical Tibb — but unlike salmon, it was not_ absent _from the tradition's world: it is a staple Nile fish, and medieval Cairo was a major centre of Arabic medicine. The honest formulation is that Nile tilapia was certainly eaten and certainly covered by the generic *samak al-nahr* (riverine fish) category of classical dietetics, while *no species-level monograph under* بلطي *has been located in the Avicennan or Ibn al-Bayṭār corpus consulted here* — which should be verified against Ibn al-Bayṭār's fish entries and against medieval Egyptian medical-dietary literature (e.g. the Cairene tradition and Jewish-Egyptian medical writing such as Maimonides' dietetic works) rather than assumed. The framework below is that of samak al-nahr, applied._ See `fish.typ` and `tibb-al-arabi.typ`.

*Names:* Arabic *بلطي (bulṭī)* — modern Egyptian, of undetermined antiquity; *مشط (mushṭ)* — Levantine, for the Galilean fish; generic *سمك (samak)*, *سمك النهر (samak al-nahr)* for river fish. Modern Arabic also uses *سمك البلطي*.

*Mizāj (of samak al-nahr, applied):* *Cold and Moist, 1st–2nd degree* per the Avicennan classification of fresh fish, with *freshwater fish read as lighter and more easily digested than marine* — *the exact inverse of the Ayurvedic reading*, where _nādī-matsya_ (riverine) is the *heavier* type. This is one of the cleanest head-on cross-system disagreements in this book, and it is left standing. Tilapia's lean, mild flesh fits the "light and easily digested" Tibb reading particularly well.

*Afʿāl (actions):* *Mughadhdhī* (nourishing); *muqawwī al-jasad* (body-strengthening); *muḥarrik al-bāh* (aphrodisiac — fish being the canonical Tibb aphrodisiac protein, converging with the Ayurvedic _vṛṣya_); *muraṭṭib* (moistening); *muḥarrik al-akhlāṭ* (humour-stirring — the standing caution that fish can bring latent disease to the surface in the susceptible, the Tibb analogue of the Chinese *發物* category).

*Istemālāt (indications):* convalescence and debility (*ḍuʿf*) — fresh, light river fish being the preferred class for the weak; sexual debility; general nourishment; the lean white-fish register for patients requiring easily digested protein.

*Mawāneʿ / Iḥtirāzāt (contraindications):* *Fish with milk* — Avicenna's explicit prohibition, converging with Caraka's _matsya-kṣīra viruddha_ (above). *Spoiled fish* — emphasized throughout the Tibb literature, with the canonical rule that *fish should be eaten the day it is caught*; the classical concern over putrefaction aligns with modern scombroid/histamine and spoilage pharmacology. Phlegmatic (*balghamī*) constitutions should take Cold-Moist fish sparingly and with warming correctives. Hot inflammatory and skin conditions, per the humour-stirring caution.

*Muṣliḥ (correctives):* the classical fish adjuvants — *vinegar (khall)*, *lemon*, *coriander (kuzbara)*, *cumin (kammūn)*, *olive oil*, *mustard*, and warming aromatics. *Egyptian practice observes these exactly:* grilled *bulṭī* is served with cumin, lemon, and often *ṭaḥīna* and a salad of herbs — i.e. the Cold-Moist fish is corrected with warming, drying, acidic adjuvants, which is the _muṣliḥ_ rule applied in a kitchen rather than a pharmacy. *Badal (substitute):* other fresh river fish — Nile perch, mullet, catfish.

*Ṭibb al-Nabawī attestation:* *none species-specific, and the general case should be stated carefully.* Fish as a class has Qur'ānic warrant — *"Lawful to you is the game of the sea and its food"* (Qur'ān 5:96) — and fish figures in the Qur'ānic narratives of Yūnus (Jonah) and of Mūsā and the youth; most Sunni schools hold all fish ḥalāl without the fins-and-scales restriction, while some Shi'i jurisprudence requires scales (which tilapia has). *But none of this is tilapia-specific*, and there is no hadith naming this fish. Recorded so that the general permissibility of fish is not mistaken for a Prophetic-medical monograph on tilapia.#footnote[Samak and samak al-nahr framework, mizāj, muṣliḥ pairings, the fish-milk prohibition, and the same-day-freshness rule: Ibn Sīnā, _al-Qānūn_ II; Ibn al-Bayṭār, _al-Jāmiʿ_; al-Rāzī, _al-Ḥāwī_ — as catalogued in `fish.typ`. Species-specific بلطي attestation *not confirmed* in the sources consulted here; flagged for verification against Ibn al-Bayṭār's fish entries and medieval Egyptian medical-dietary literature, including Maimonides' dietetic writings. Qur'ān 5:96 on sea-game; the fins-and-scales divergence between Sunni and some Shi'i positions: see `fish.typ`.]

== Classical Formulas & Preparations

=== Chinese medicine (中醫)

*No classical formula* — the species postdates the canon. Two registers are worth recording:
- *The living substitution into a classical slot:* *鯽魚湯 (jìyú tāng)*, crucian-carp soup, is the classical postpartum lactation-and-recovery preparation; modern Chinese households routinely make the same soup with tilapia, with ginger and sometimes _Astragalus_ or jujube. This is *folk substitution of a new fish into an old formula-slot*, documented as current practice rather than as classical text — and it is precisely the mechanism by which an introduced food acquires traditional standing.
- *Modern Chinese cooking:* *清蒸罗非鱼* (steamed whole with scallion, ginger, and soy — the standard Cantonese treatment, and the one that best suits a mild lean fish), *豆豉蒸* (steamed with fermented black bean), braised and fried preparations. Ginger-and-scallion accompaniment is the culinary form of the classical warming correction for a neutral-to-cool freshwater fish.

=== Ayurveda

*No classical formula* — fish is a dietary article (_āhāra_) rather than a compound-formula ingredient in the saṃhitā pharmacy. The classical preparation register that applies is dietetic: fish as *māṃsa-rasa* (meat soup/broth), the convalescent preparation par excellence, given in Vāta-depletion and post-illness recovery; light cooking with _dīpana_ spices (cumin, coriander, black pepper, ginger) is the classical accompaniment logic, matching both the Tibb _muṣliḥ_ and the Chinese ginger-scallion practice. Regionally, tilapia is now farmed in India and Bangladesh and enters Bengali and Keralan fish cookery — *modern, and worth distinguishing from classical attestation*: Bengali and Keralan Hindu communities have eaten fish for centuries, but not this fish.

=== Western / Greco-Roman and later European medicine

*No Greco-Roman pharmacological entry for the species* — tilapia is not a Mediterranean fish, and Dioscorides, Pliny, and Galen treat the fish they knew (see `fish.typ`). Three substantive non-Greco-Roman Western-adjacent registers:
- *Ancient and modern Egyptian preparation.* Egypt had a large pharaonic fish-salting and drying industry (the Nile flood fishery supplied salted fish as a staple and a trade good), and the modern Egyptian register continues a recognizably ancient pattern: *bulṭī mashwī* (grilled whole, cumin and lemon), *bulṭī maqlī* (fried), and fish in *ṭaḥīna*-based sauces. (Egypt's famous fermented-salted fish, *fasīkh*, is traditionally made with mullet rather than tilapia, but belongs to the same continuous preservation tradition — see the fermentation section of `fish.typ`.)
- *Galilean / Levantine.* *St. Peter's fish* served *fried whole with lemon* on the shores of Lake Kinneret — a pilgrimage-and-tourism cuisine of modern construction built on a genuine ancient fishery.
- *Modern Western commodity cookery.* Tilapia reaches Europe and North America almost entirely as *frozen or fresh fillet*, treated as a neutral white-fish canvas — breaded, blackened, baked, taco-fried. The near-absence of a culinary tradition is itself the point: tilapia is the first major food fish to be globalized *as a commodity protein rather than as a cuisine*.

=== Tibb (Arabic-Islamic)

Covered above: *samak al-nahr* dietetics with the canonical *muṣliḥ* pairings, which Egyptian grilled-bulṭī practice observes precisely. The classical medical preparation of the category is *mā' al-samak* — fish broth for convalescent debility (the direct Tibb counterpart of the Ayurvedic _māṃsa-rasa_ and of Chinese fish soup, a three-way convergence on fish broth as the convalescent food).

== Climate, Constitution & Regional Diet

Tilapia's climate story is distinctive in this book: a fish of *hot* waters whose thermal tolerance (roughly 20–35 °C optimum, with poor survival below ~12 °C) *determines its entire global distribution*, both traditional and modern. Where it is farmed outside the tropics, it is farmed in heated or geothermal water — i.e. the climate constraint is bought off with energy. See `climates.typ`.

=== Hot-arid riverine (the Nile — the native and ancient zone)

Köppen BWh with a great river running through it: extreme heat, negligible rainfall, intense dryness; external *燥* and *熱*, Pitta-dominant, with Vāta aggravated by dryness. *Traditional preparation and cares.* The classical Egyptian and modern Egyptian register is *grilling* and *salting/drying* — and the constitutive accompaniments are *cumin, lemon, herbs, ṭaḥīna, and raw onion*, i.e. precisely the warming-drying-acidic *muṣliḥ* set that classical Tibb prescribes for a Cold-Moist food. In a hot-dry climate a cooling-moistening protein is *climatically apt* (Tibb reading), while the Ayurvedic reading of fish as uṣṇa would make it Pitta-provoking in exactly this climate — the two systems' disagreement about fish has real consequences here, and the Egyptian kitchen's answer (abundant lemon, herbs, and salad alongside) hedges both ways.

=== Levantine Mediterranean (the Galilee)

Köppen Csa: hot dry summers, cool wet winters. The Kinneret fishery is ancient and continuous; the preparation is *fried whole with lemon*, eaten with bread and salads — again the acidic corrective. Constitutionally the summer carries Pitta and 熱; the fish's lightness suits it.

=== Hot-humid tropical (the modern aquaculture heartland: Brazil, Southeast Asia, sub-Saharan Africa)

Köppen Af/Am/Aw: this is where tilapia farming actually happens at scale, because the water is warm year-round and no heating is needed. External *濕熱*; Pitta-Kapha, Spleen-loaded per `climates.typ`. *Traditional and emerging preparations:* Brazilian *tilápia na brasa* and *frita*, and tilapia entering *moqueca* (with palm oil, coconut milk, coriander, lime — see `fish.typ`); West and East African grilled and stewed preparations; Southeast Asian fried-whole-with-chilli-and-lime and sour-soup treatments. *The cares are convergent and instructive:* every one of these traditions pairs the fish with *acid (lime, tamarind, tomato) and pungent aromatics (chilli, ginger, coriander, garlic)* — in a hot-humid climate this is simultaneously the Tibb *muṣliḥ* logic, the Ayurvedic _dīpana_ accompaniment for a heavy-moist food in a weak-_agni_ climate, and food-safety practice in a hot climate. Three rationales, one plate.

=== Temperate zones (China's main production belt, the US, Europe — the commodity register)

Köppen Cfa/Cwa and colder. Production here is in heated, recirculating, or geothermally warmed systems, or else the fish is simply *imported frozen*; consumption is detached from any local tradition and from any seasonal logic. *This is the zone where the substance has no climatic register at all* — a genuinely modern condition, and the honest description of how most tilapia is now eaten.

=== Modern transposition (_deśa-viruddha_ / _kāla-viruddha_, Caraka Sūtra 26)

Tilapia is an unusually pure case of transposition, since the fish itself has been transposed — not merely its preparations. Three observations. First, *the classical correctives travelled with the fish and arrived independently*: Egyptian cumin-and-lemon, Brazilian lime-and-coriander, Cantonese ginger-and-scallion, Southeast Asian tamarind-and-chilli are the same _muṣliḥ_/_dīpana_ solution reinvented in four kitchens, which is strong practical evidence that the classical reasoning tracks something real about preparing a mild, moist, freshwater protein. Second, *the modern commodity register strips those correctives*: a frozen fillet baked plain in a temperate kitchen is the fish without its traditional corrections — not harmful, but the first form of tilapia consumption in history to be culturally and climatically unanchored. Third, and most substantively, the *nutritional transposition* matters more than the climatic one: tilapia is widely eaten *as though it were oily fish*, when its omega-3 content is an order of magnitude lower — a _sampad-viruddha_ (wrong-substance) error with real public-health consequence, since the health claim attached to "eat more fish" does not transfer to this fish. See `climates.typ`, `fish.typ`.

== Modern Nutrition & Pharmacology

Composition, tilapia, cooked (dry heat), approximate per 100 g — *verify against USDA FoodData Central*; farmed-fish composition varies substantially with feed and producer.

- Energy ~128 kcal; Water ~72 g
- *Protein ~26 g* — complete amino-acid profile; a *high protein-to-calorie ratio*, among the leanest commonly eaten fish
- *Fat ~2.7 g* — genuinely lean (cf. salmon ~13 g, sardines ~11 g)
- *Long-chain omega-3 (EPA + DHA) ~0.1–0.2 g* — *the critical figure*: roughly a tenth of salmon's or sardines'; tilapia is *not* a meaningful omega-3 source
- *Omega-6 (incl. arachidonic acid)* — relatively high for a fish, feed-dependent (see below)
- Selenium ~45–55 µg (substantial); Vitamin B12 ~1.5–2 µg; Niacin ~4 mg; Phosphorus ~200 mg; Potassium ~380 mg
- Vitamin D — low (unlike oily cold-water fish)
- Purines — moderate

*Pharmacology and food-science points of note:*
- *The fatty-acid controversy, stated in full.* The 2008 Weaver et al. analysis (above) found farmed tilapia high in arachidonic acid relative to EPA/DHA and framed this unfavourably against bacon and hamburger. *The finding is real and feed-driven* — corn-and-soy-based pellets produce an omega-6-rich fillet, and a farm feeding fish oil or algal meal produces a different profile; *the framing was overstated*, since a ratio comparison ignores tilapia's leanness, low mercury, high protein, and absence of processing. The defensible conclusion: *tilapia is a good lean protein and a poor omega-3 source, and its omega-6 load is a property of how it is fed rather than of what it is.*
- *Mercury and contaminants — a real advantage.* Short lifespan, low trophic position, and controlled feed give tilapia consistently low methylmercury, placing it in the "Best Choices" category for pregnancy and childhood; PCB and dioxin levels are likewise generally low relative to wild fatty fish from contaminated waters. See `fish.typ`.
- *Selenium* — a genuinely notable contribution (one serving approaches or exceeds daily requirements), relevant to antioxidant-enzyme function.
- *Protein quality* — complete and highly digestible; the basis of tilapia's role in protein-deficiency contexts.
- *Aquaculture and food security — why this fish matters disproportionately.* Tilapia is sometimes called the *"aquatic chicken"*: it grows fast, tolerates crowding, poor water quality, and low dissolved oxygen, feeds low on the food chain (reducing the wild-fish-input problem that dogs carnivorous aquaculture), and has been subject to sustained genetic improvement — the *GIFT (Genetically Improved Farmed Tilapia)* program, developed from the 1980s by WorldFish and partners, is one of the most consequential aquaculture breeding efforts in history and underpins much of Asian and African production. For a book otherwise concerned with classical pharmacology, this matters: *tilapia's significance is nutritional-epidemiological rather than pharmacological* — accessible animal protein at low cost in low- and middle-income countries.
- *Ecological cost, held in the same frame.* The same traits that make it a successful farmed fish make it a successful invader: tilapia is established as an invasive species across the tropics and subtropics, with documented displacement of native fish in Brazil, Mexico, the Philippines, and elsewhere. *The food-security benefit and the ecological harm are both real and should not be traded off rhetorically.*
- *Antibiotics and husbandry* — variable by producer and jurisdiction; certification (ASC) is the practical consumer tool, imperfect but meaningful.#footnote[Composition: USDA FoodData Central — verify. Fatty-acid controversy: Weaver, K. L. et al. (2008), _Journal of the American Dietetic Association_, and subsequent more qualified reviews; the feed-dependence of the omega-6 profile is well established. Mercury category: FDA/EPA "Best Choices." GIFT program: WorldFish and associated aquaculture-genetics literature. Invasive-species impacts: conservation literature across Brazil, Mexico, the Philippines and elsewhere. Aquaculture antibiotic use and certification: current FAO/ASC sources. All modern figures and regulatory positions require current verification.]

*Safe daily / weekly intake:*
- *General adults:* fits comfortably within the standard 2–3 servings/week fish recommendation, *but should not be counted toward the oily-fish portion of that advice* — pair with or substitute sardines, salmon, or mackerel if long-chain omega-3 intake is the goal (see `sardines.typ`, `salmon.typ`).
- *Pregnancy and children:* appropriate and low-mercury; the same omega-3 caveat applies, and matters most here, since the fetal-neurodevelopmental rationale for fish in pregnancy is specifically an EPA/DHA rationale.
- *Gout-susceptible individuals:* moderate purines; less restrictive than sardines or anchovies.
- *Fish allergy:* avoid (parvalbumin cross-reactivity).
- *Sourcing:* prefer certified or known producers; the species' safety profile is good, its husbandry variance is the real variable.
- *Reference figures, not personalized medical advice.*

== Sources

- Trewavas, _Tilapiine Fishes of the Genera Sarotherodon, Oreochromis and Danakilia_ (British Museum, Natural History, 1983); Smith, _Illustrations of the Zoology of South Africa_ (1840) for the genus name; FishBase etymology.
- Houlihan, _The Animal World of the Pharaohs_ (Thames & Hudson, 1996); Gamer-Wallert, _Fische und Fischkulte im alten Ägypten_ (1970) — Egyptian fish iconography, the tilapia-rebirth association, and the qualified Abtu identification.
- Matthew 17:24–27, Greek New Testament; Leviticus 11:9–12; Qur'ān 5:96; Nathan, _The Foods of Israel Today_ (2001) — the "St. Peter's fish" modern naming and the dietary-law framework.
- Caraka Saṃhitā, Sūtrasthāna 27 (matsya) and 26 (viruddhāhāra); Suśruta Saṃhitā, Sūtrasthāna 46; Bhāvaprakāśa Nighaṇṭu, _Māṃsa-varga_ — Sharma & Dash, Murthy translations.
- Ibn Sīnā, _al-Qānūn fī al-Ṭibb_ II (samak, samak al-nahr); Ibn al-Bayṭār, _al-Jāmiʿ_; al-Rāzī, _al-Ḥāwī_ — the samak framework applied here; species-specific بلطي attestation flagged as unverified.
- Li Shizhen, _Bencao Gangmu_ (本草綱目), 1578, fish section (for 鯽魚, 鯉魚, the reasoned anchors); Bensky, Clavey & Stöger, _Materia Medica_, 3rd ed.
- FAO aquaculture statistics and country reports (China, Brazil, Egypt); Embrapa Pesca e Aquicultura (Brazil); WorldFish GIFT program literature.
- Weaver, K. L. et al. (2008), _Journal of the American Dietetic Association_, on farmed-fish fatty-acid profiles — and subsequent qualified reviews; verify.
- USDA FoodData Central; FDA/EPA "Best Choices" fish advice; ASC certification criteria.
- Brazilian and international conservation literature on _Oreochromis niloticus_ as an invasive species — verify against current ICMBio/IBAMA assessments.
- Foundational and sibling frameworks: `fish.typ` (the cross-cutting matsya / samak / Bencao-fish and safety frameworks this entry applies), `tibb-al-arabi.typ`, `climates.typ`, `zz-glossary.typ`; parallel species entries `salmon.typ`, `sardines.typ`.
